/* eslint-disable one-var, sort-vars */
import type { MapScope } from "./map-scopes";

/* Atlas names are aligned to the bundled world-countries-110m topology. */
export const regionalWorldCountryNames: Readonly<
    Record<Exclude<MapScope, "global" | "north-america">, ReadonlySet<string>>
  > = {
    africa: new Set([
      "Tanzania",
      "W. Sahara",
      "Dem. Rep. Congo",
      "Somalia",
      "Kenya",
      "Sudan",
      "Chad",
      "South Africa",
      "Lesotho",
      "Zimbabwe",
      "Botswana",
      "Namibia",
      "Senegal",
      "Mali",
      "Mauritania",
      "Benin",
      "Niger",
      "Nigeria",
      "Cameroon",
      "Togo",
      "Ghana",
      "Guinea",
      "Guinea-Bissau",
      "Liberia",
      "Sierra Leone",
      "Burkina Faso",
      "Central African Rep.",
      "Congo",
      "Gabon",
      "Eq. Guinea",
      "Zambia",
      "Malawi",
      "Mozambique",
      "eSwatini",
      "Angola",
      "Burundi",
      "Madagascar",
      "Gambia",
      "Tunisia",
      "Algeria",
      "Eritrea",
      "Morocco",
      "Egypt",
      "Libya",
      "Ethiopia",
      "Djibouti",
      "Uganda",
      "Rwanda",
      "S. Sudan",
    ]),
    asia: new Set([
      "Kazakhstan",
      "Uzbekistan",
      "Indonesia",
      "Timor-Leste",
      "Israel",
      "Lebanon",
      "Palestine",
      "Jordan",
      "United Arab Emirates",
      "Qatar",
      "Kuwait",
      "Iraq",
      "Oman",
      "Cambodia",
      "Thailand",
      "Laos",
      "Myanmar",
      "Vietnam",
      "North Korea",
      "South Korea",
      "Mongolia",
      "India",
      "Bangladesh",
      "Bhutan",
      "Nepal",
      "Pakistan",
      "Afghanistan",
      "Tajikistan",
      "Kyrgyzstan",
      "Turkmenistan",
      "Iran",
      "Syria",
      "Armenia",
      "Turkey",
      "Sri Lanka",
      "China",
      "Taiwan",
      "Azerbaijan",
      "Georgia",
      "Philippines",
      "Malaysia",
      "Brunei",
      "Japan",
      "Yemen",
      "Saudi Arabia",
    ]),
    europe: new Set([
      "Russia",
      "Norway",
      "France",
      "Sweden",
      "Belarus",
      "Ukraine",
      "Poland",
      "Austria",
      "Hungary",
      "Moldova",
      "Romania",
      "Lithuania",
      "Latvia",
      "Estonia",
      "Germany",
      "Bulgaria",
      "Greece",
      "Albania",
      "Croatia",
      "Switzerland",
      "Luxembourg",
      "Belgium",
      "Netherlands",
      "Portugal",
      "Spain",
      "Ireland",
      "Italy",
      "Denmark",
      "United Kingdom",
      "Iceland",
      "Slovenia",
      "Finland",
      "Slovakia",
      "Czechia",
      "Cyprus",
      "Bosnia and Herz.",
      "Macedonia",
      "Serbia",
      "Montenegro",
      "Kosovo",
    ]),
    "latin-america": new Set([
      "Argentina",
      "Chile",
      "Haiti",
      "Dominican Rep.",
      "Bahamas",
      "Falkland Is.",
      "Uruguay",
      "Brazil",
      "Bolivia",
      "Peru",
      "Colombia",
      "Panama",
      "Costa Rica",
      "Nicaragua",
      "Honduras",
      "El Salvador",
      "Guatemala",
      "Belize",
      "Venezuela",
      "Guyana",
      "Suriname",
      "Ecuador",
      "Puerto Rico",
      "Jamaica",
      "Cuba",
      "Paraguay",
      "Trinidad and Tobago",
    ]),
    oceania: new Set([
      "Fiji",
      "Papua New Guinea",
      "Vanuatu",
      "New Caledonia",
      "Solomon Is.",
      "New Zealand",
      "Australia",
    ]),
  },
  isWorldCountryInMapScope = (
    mapScope: MapScope,
    countryName: string
  ): boolean =>
    mapScope === "global" || mapScope === "north-america"
      ? true
      : regionalWorldCountryNames[mapScope].has(countryName);
