/* eslint-disable one-var */

"use client";

const DERIVATIVE_WIDTHS = [320, 640, 1280] as const,
  // Mirrors the objectKey prefixes the media route serves (uploads/,
  // profiles/, projects/, tracks/) so third-party CDNs never receive
  // derivative candidates.
  MEDIA_IMAGE_PATH_PATTERN =
    /\/media\/(?:uploads|profiles|projects|tracks)\/.+?\.(?:avif|gif|jpe?g|png|webp)$/iu,
  REMOTE_IMAGE_URL_PATTERN = /^https?:\/\//u;

export interface MediaImageSrcProps {
  sizes: string;
  srcSet: string;
}

/**
 * Builds a responsive `srcset` for SoundKit media image URLs. Originals in R2
 * get `.{width}w.webp` derivatives generated by the media-processor container,
 * and the media route redirects to the original until a derivative exists —
 * so these candidates are always renderable, before and after backfill.
 *
 * Non-media or extension-less sources return null and keep their existing
 * rendering path.
 */
export const mediaImageSrcProps = (src: string): MediaImageSrcProps | null => {
  if (
    !REMOTE_IMAGE_URL_PATTERN.test(src) ||
    !MEDIA_IMAGE_PATH_PATTERN.test(src)
  ) {
    return null;
  }

  return {
    sizes: "(max-width: 768px) 96px, 48px",
    srcSet: DERIVATIVE_WIDTHS.map(
      (widthPx) => `${src}.${widthPx}w.webp ${widthPx}w`
    ).join(", "),
  };
};
