/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SitemapDotxmlRouteImport } from './app/sitemap[.]xml'
import { Route as SignupRouteImport } from './app/signup'
import { Route as PricingRouteImport } from './app/pricing'
import { Route as LoginRouteImport } from './app/login'
import { Route as LlmsDottxtRouteImport } from './app/llms[.]txt'
import { Route as DashboardRouteImport } from './app/dashboard'
import { Route as ExploreRouteImport } from './app/_explore'
import { Route as DashboardIndexRouteImport } from './app/dashboard/index'
import { Route as ExploreIndexRouteImport } from './app/_explore/index'
import { Route as DashboardTeamRouteImport } from './app/dashboard/team'
import { Route as DashboardProfileRouteImport } from './app/dashboard/profile'
import { Route as DashboardMusicRouteImport } from './app/dashboard/music'
import { Route as DashboardMessagesRouteImport } from './app/dashboard/messages'
import { Route as DashboardFinanceRouteImport } from './app/dashboard/finance'
import { Route as DashboardCommunityRouteImport } from './app/dashboard/community'
import { Route as DashboardCollaboratorsRouteImport } from './app/dashboard/collaborators'
import { Route as DashboardBillingRouteImport } from './app/dashboard/billing'
import { Route as DashboardAdminRouteImport } from './app/dashboard/admin'
import { Route as ExploreNewReleasesRouteImport } from './app/_explore/new-releases'
import { Route as ExploreLiveRouteImport } from './app/_explore/live'
import { Route as DashboardVideosIndexRouteImport } from './app/dashboard/videos/index'
import { Route as DashboardTracksIndexRouteImport } from './app/dashboard/tracks/index'
import { Route as DashboardProjectsIndexRouteImport } from './app/dashboard/projects/index'
import { Route as DashboardOpenVersesIndexRouteImport } from './app/dashboard/open-verses/index'
import { Route as DashboardLiveIndexRouteImport } from './app/dashboard/live/index'
import { Route as ExploreVideosIndexRouteImport } from './app/_explore/videos/index'
import { Route as ExploreTracksIndexRouteImport } from './app/_explore/tracks/index'
import { Route as ExploreLiveIndexRouteImport } from './app/_explore/live/index'
import { Route as ExploreLibraryIndexRouteImport } from './app/_explore/library/index'
import { Route as ExploreGenresIndexRouteImport } from './app/_explore/genres/index'
import { Route as ExploreCommunitiesIndexRouteImport } from './app/_explore/communities/index'
import { Route as ExploreArtistIndexRouteImport } from './app/_explore/artist/index'
import { Route as SignupFanOnboardingRouteImport } from './app/signup/fan/onboarding'
import { Route as SignupFanCredentialsRouteImport } from './app/signup/fan/credentials'
import { Route as SignupArtistOnboardingRouteImport } from './app/signup/artist/onboarding'
import { Route as SignupArtistCredentialsRouteImport } from './app/signup/artist/credentials'
import { Route as DashboardVideosNewRouteImport } from './app/dashboard/videos/new'
import { Route as DashboardTracksNewRouteImport } from './app/dashboard/tracks/new'
import { Route as DashboardProjectsNewRouteImport } from './app/dashboard/projects/new'
import { Route as DashboardProjectsIdRouteImport } from './app/dashboard/projects/$id'
import { Route as DashboardOpenVersesNewRouteImport } from './app/dashboard/open-verses/new'
import { Route as DashboardOpenVersesGenreRouteImport } from './app/dashboard/open-verses/$genre'
import { Route as DashboardLiveUpcomingRouteImport } from './app/dashboard/live/upcoming'
import { Route as DashboardLiveStreamsRouteImport } from './app/dashboard/live/streams'
import { Route as DashboardLivePartiesRouteImport } from './app/dashboard/live/parties'
import { Route as DashboardLiveMyKitRouteImport } from './app/dashboard/live/my-kit'
import { Route as DashboardLiveFindRouteImport } from './app/dashboard/live/find'
import { Route as DashboardLiveChallengeRouteImport } from './app/dashboard/live/challenge'
import { Route as DashboardCareerSettingsRouteImport } from './app/dashboard/career/settings'
import { Route as DashboardCareerProfileRouteImport } from './app/dashboard/career/profile'
import { Route as DashboardCareerCalendarRouteImport } from './app/dashboard/career/calendar'
import { Route as DashboardCareerAnalyticsRouteImport } from './app/dashboard/career/analytics'
import { Route as DashboardCareerAiStudioRouteImport } from './app/dashboard/career/ai-studio'
import { Route as ExploreVideosIdRouteImport } from './app/_explore/videos/$id'
import { Route as ExploreTracksIdRouteImport } from './app/_explore/tracks/$id'
import { Route as ExploreProjectsIdRouteImport } from './app/_explore/projects/$id'
import { Route as ExploreLibrarySettingsRouteImport } from './app/_explore/library/settings'
import { Route as ExploreGenresIdRouteImport } from './app/_explore/genres/$id'
import { Route as ExploreArtistTopRouteImport } from './app/_explore/artist/top'
import { Route as ExploreArtistRisingStarsRouteImport } from './app/_explore/artist/rising-stars'
import { Route as ExploreArtistNewRouteImport } from './app/_explore/artist/new'
import { Route as ExploreArtistUsernameRouteImport } from './app/_explore/artist/$username'
import { Route as DashboardTracksIdIndexRouteImport } from './app/dashboard/tracks/$id/index'
import { Route as DashboardLiveMyStatsIndexRouteImport } from './app/dashboard/live/my-stats/index'
import { Route as ExploreLiveStreamsIndexRouteImport } from './app/_explore/live/streams/index'
import { Route as ExploreLivePartiesIndexRouteImport } from './app/_explore/live/parties/index'
import { Route as ExploreLiveBattlesIndexRouteImport } from './app/_explore/live/battles/index'
import { Route as ExploreLibraryWatchedIndexRouteImport } from './app/_explore/library/watched/index'
import { Route as ExploreLibrarySavedIndexRouteImport } from './app/_explore/library/saved/index'
import { Route as ExploreLibraryRecentIndexRouteImport } from './app/_explore/library/recent/index'
import { Route as ExploreLibraryPurchasedIndexRouteImport } from './app/_explore/library/purchased/index'
import { Route as ExploreLibraryPlaylistsIndexRouteImport } from './app/_explore/library/playlists/index'
import { Route as DashboardTracksIdEditRouteImport } from './app/dashboard/tracks/$id/edit'
import { Route as DashboardOpenVersesGenreIdRouteImport } from './app/dashboard/open-verses/$genre/$id'
import { Route as ExploreLiveStreamsIdRouteImport } from './app/_explore/live/streams/$id'
import { Route as ExploreLivePartiesIdRouteImport } from './app/_explore/live/parties/$id'
import { Route as ExploreLiveBattlesUpcomingRouteImport } from './app/_explore/live/battles/upcoming'
import { Route as ExploreLiveBattlesMustSeeRouteImport } from './app/_explore/live/battles/must-see'
import { Route as ExploreLiveBattlesLeaderboardRouteImport } from './app/_explore/live/battles/leaderboard'
import { Route as ExploreLiveBattlesIdRouteImport } from './app/_explore/live/battles/$id'
import { Route as ExploreLibraryPlaylistsIdIndexRouteImport } from './app/_explore/library/playlists/$id/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/_explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExploreRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMusicRoute = DashboardMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanceRoute = DashboardFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommunityRoute = DashboardCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCollaboratorsRoute = DashboardCollaboratorsRouteImport.update({
  id: '/collaborators',
  path: '/collaborators',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const ExploreNewReleasesRoute = ExploreNewReleasesRouteImport.update({
  id: '/new-releases',
  path: '/new-releases',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreLiveRoute = ExploreLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ExploreRoute,
} as any)
const DashboardVideosIndexRoute = DashboardVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTracksIndexRoute = DashboardTracksIndexRouteImport.update({
  id: '/tracks/',
  path: '/tracks/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOpenVersesIndexRoute =
  DashboardOpenVersesIndexRouteImport.update({
    id: '/open-verses/',
    path: '/open-verses/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLiveIndexRoute = DashboardLiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => DashboardRoute,
} as any)
const ExploreVideosIndexRoute = ExploreVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreTracksIndexRoute = ExploreTracksIndexRouteImport.update({
  id: '/tracks/',
  path: '/tracks/',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreLiveIndexRoute = ExploreLiveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExploreLiveRoute,
} as any)
const ExploreLibraryIndexRoute = ExploreLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreGenresIndexRoute = ExploreGenresIndexRouteImport.update({
  id: '/genres/',
  path: '/genres/',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreCommunitiesIndexRoute = ExploreCommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreArtistIndexRoute = ExploreArtistIndexRouteImport.update({
  id: '/artist/',
  path: '/artist/',
  getParentRoute: () => ExploreRoute,
} as any)
const SignupFanOnboardingRoute = SignupFanOnboardingRouteImport.update({
  id: '/fan/onboarding',
  path: '/fan/onboarding',
  getParentRoute: () => SignupRoute,
} as any)
const SignupFanCredentialsRoute = SignupFanCredentialsRouteImport.update({
  id: '/fan/credentials',
  path: '/fan/credentials',
  getParentRoute: () => SignupRoute,
} as any)
const SignupArtistOnboardingRoute = SignupArtistOnboardingRouteImport.update({
  id: '/artist/onboarding',
  path: '/artist/onboarding',
  getParentRoute: () => SignupRoute,
} as any)
const SignupArtistCredentialsRoute = SignupArtistCredentialsRouteImport.update({
  id: '/artist/credentials',
  path: '/artist/credentials',
  getParentRoute: () => SignupRoute,
} as any)
const DashboardVideosNewRoute = DashboardVideosNewRouteImport.update({
  id: '/videos/new',
  path: '/videos/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTracksNewRoute = DashboardTracksNewRouteImport.update({
  id: '/tracks/new',
  path: '/tracks/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIdRoute = DashboardProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOpenVersesNewRoute = DashboardOpenVersesNewRouteImport.update({
  id: '/open-verses/new',
  path: '/open-verses/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOpenVersesGenreRoute =
  DashboardOpenVersesGenreRouteImport.update({
    id: '/open-verses/$genre',
    path: '/open-verses/$genre',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLiveUpcomingRoute = DashboardLiveUpcomingRouteImport.update({
  id: '/live/upcoming',
  path: '/live/upcoming',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLiveStreamsRoute = DashboardLiveStreamsRouteImport.update({
  id: '/live/streams',
  path: '/live/streams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLivePartiesRoute = DashboardLivePartiesRouteImport.update({
  id: '/live/parties',
  path: '/live/parties',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLiveMyKitRoute = DashboardLiveMyKitRouteImport.update({
  id: '/live/my-kit',
  path: '/live/my-kit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLiveFindRoute = DashboardLiveFindRouteImport.update({
  id: '/live/find',
  path: '/live/find',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLiveChallengeRoute = DashboardLiveChallengeRouteImport.update({
  id: '/live/challenge',
  path: '/live/challenge',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCareerSettingsRoute = DashboardCareerSettingsRouteImport.update({
  id: '/career/settings',
  path: '/career/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCareerProfileRoute = DashboardCareerProfileRouteImport.update({
  id: '/career/profile',
  path: '/career/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCareerCalendarRoute = DashboardCareerCalendarRouteImport.update({
  id: '/career/calendar',
  path: '/career/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCareerAnalyticsRoute =
  DashboardCareerAnalyticsRouteImport.update({
    id: '/career/analytics',
    path: '/career/analytics',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCareerAiStudioRoute = DashboardCareerAiStudioRouteImport.update({
  id: '/career/ai-studio',
  path: '/career/ai-studio',
  getParentRoute: () => DashboardRoute,
} as any)
const ExploreVideosIdRoute = ExploreVideosIdRouteImport.update({
  id: '/videos/$id',
  path: '/videos/$id',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreTracksIdRoute = ExploreTracksIdRouteImport.update({
  id: '/tracks/$id',
  path: '/tracks/$id',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreProjectsIdRoute = ExploreProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreLibrarySettingsRoute = ExploreLibrarySettingsRouteImport.update({
  id: '/library/settings',
  path: '/library/settings',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreGenresIdRoute = ExploreGenresIdRouteImport.update({
  id: '/genres/$id',
  path: '/genres/$id',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreArtistTopRoute = ExploreArtistTopRouteImport.update({
  id: '/artist/top',
  path: '/artist/top',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreArtistRisingStarsRoute =
  ExploreArtistRisingStarsRouteImport.update({
    id: '/artist/rising-stars',
    path: '/artist/rising-stars',
    getParentRoute: () => ExploreRoute,
  } as any)
const ExploreArtistNewRoute = ExploreArtistNewRouteImport.update({
  id: '/artist/new',
  path: '/artist/new',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreArtistUsernameRoute = ExploreArtistUsernameRouteImport.update({
  id: '/artist/$username',
  path: '/artist/$username',
  getParentRoute: () => ExploreRoute,
} as any)
const DashboardTracksIdIndexRoute = DashboardTracksIdIndexRouteImport.update({
  id: '/tracks/$id/',
  path: '/tracks/$id/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLiveMyStatsIndexRoute =
  DashboardLiveMyStatsIndexRouteImport.update({
    id: '/live/my-stats/',
    path: '/live/my-stats/',
    getParentRoute: () => DashboardRoute,
  } as any)
const ExploreLiveStreamsIndexRoute = ExploreLiveStreamsIndexRouteImport.update({
  id: '/streams/',
  path: '/streams/',
  getParentRoute: () => ExploreLiveRoute,
} as any)
const ExploreLivePartiesIndexRoute = ExploreLivePartiesIndexRouteImport.update({
  id: '/parties/',
  path: '/parties/',
  getParentRoute: () => ExploreLiveRoute,
} as any)
const ExploreLiveBattlesIndexRoute = ExploreLiveBattlesIndexRouteImport.update({
  id: '/battles/',
  path: '/battles/',
  getParentRoute: () => ExploreLiveRoute,
} as any)
const ExploreLibraryWatchedIndexRoute =
  ExploreLibraryWatchedIndexRouteImport.update({
    id: '/library/watched/',
    path: '/library/watched/',
    getParentRoute: () => ExploreRoute,
  } as any)
const ExploreLibrarySavedIndexRoute =
  ExploreLibrarySavedIndexRouteImport.update({
    id: '/library/saved/',
    path: '/library/saved/',
    getParentRoute: () => ExploreRoute,
  } as any)
const ExploreLibraryRecentIndexRoute =
  ExploreLibraryRecentIndexRouteImport.update({
    id: '/library/recent/',
    path: '/library/recent/',
    getParentRoute: () => ExploreRoute,
  } as any)
const ExploreLibraryPurchasedIndexRoute =
  ExploreLibraryPurchasedIndexRouteImport.update({
    id: '/library/purchased/',
    path: '/library/purchased/',
    getParentRoute: () => ExploreRoute,
  } as any)
const ExploreLibraryPlaylistsIndexRoute =
  ExploreLibraryPlaylistsIndexRouteImport.update({
    id: '/library/playlists/',
    path: '/library/playlists/',
    getParentRoute: () => ExploreRoute,
  } as any)
const DashboardTracksIdEditRoute = DashboardTracksIdEditRouteImport.update({
  id: '/tracks/$id/edit',
  path: '/tracks/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOpenVersesGenreIdRoute =
  DashboardOpenVersesGenreIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DashboardOpenVersesGenreRoute,
  } as any)
const ExploreLiveStreamsIdRoute = ExploreLiveStreamsIdRouteImport.update({
  id: '/streams/$id',
  path: '/streams/$id',
  getParentRoute: () => ExploreLiveRoute,
} as any)
const ExploreLivePartiesIdRoute = ExploreLivePartiesIdRouteImport.update({
  id: '/parties/$id',
  path: '/parties/$id',
  getParentRoute: () => ExploreLiveRoute,
} as any)
const ExploreLiveBattlesUpcomingRoute =
  ExploreLiveBattlesUpcomingRouteImport.update({
    id: '/battles/upcoming',
    path: '/battles/upcoming',
    getParentRoute: () => ExploreLiveRoute,
  } as any)
const ExploreLiveBattlesMustSeeRoute =
  ExploreLiveBattlesMustSeeRouteImport.update({
    id: '/battles/must-see',
    path: '/battles/must-see',
    getParentRoute: () => ExploreLiveRoute,
  } as any)
const ExploreLiveBattlesLeaderboardRoute =
  ExploreLiveBattlesLeaderboardRouteImport.update({
    id: '/battles/leaderboard',
    path: '/battles/leaderboard',
    getParentRoute: () => ExploreLiveRoute,
  } as any)
const ExploreLiveBattlesIdRoute = ExploreLiveBattlesIdRouteImport.update({
  id: '/battles/$id',
  path: '/battles/$id',
  getParentRoute: () => ExploreLiveRoute,
} as any)
const ExploreLibraryPlaylistsIdIndexRoute =
  ExploreLibraryPlaylistsIdIndexRouteImport.update({
    id: '/library/playlists/$id/',
    path: '/library/playlists/$id/',
    getParentRoute: () => ExploreRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ExploreIndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/live': typeof ExploreLiveRouteWithChildren
  '/new-releases': typeof ExploreNewReleasesRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/collaborators': typeof DashboardCollaboratorsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/music': typeof DashboardMusicRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/artist/$username': typeof ExploreArtistUsernameRoute
  '/artist/new': typeof ExploreArtistNewRoute
  '/artist/rising-stars': typeof ExploreArtistRisingStarsRoute
  '/artist/top': typeof ExploreArtistTopRoute
  '/genres/$id': typeof ExploreGenresIdRoute
  '/library/settings': typeof ExploreLibrarySettingsRoute
  '/projects/$id': typeof ExploreProjectsIdRoute
  '/tracks/$id': typeof ExploreTracksIdRoute
  '/videos/$id': typeof ExploreVideosIdRoute
  '/dashboard/career/ai-studio': typeof DashboardCareerAiStudioRoute
  '/dashboard/career/analytics': typeof DashboardCareerAnalyticsRoute
  '/dashboard/career/calendar': typeof DashboardCareerCalendarRoute
  '/dashboard/career/profile': typeof DashboardCareerProfileRoute
  '/dashboard/career/settings': typeof DashboardCareerSettingsRoute
  '/dashboard/live/challenge': typeof DashboardLiveChallengeRoute
  '/dashboard/live/find': typeof DashboardLiveFindRoute
  '/dashboard/live/my-kit': typeof DashboardLiveMyKitRoute
  '/dashboard/live/parties': typeof DashboardLivePartiesRoute
  '/dashboard/live/streams': typeof DashboardLiveStreamsRoute
  '/dashboard/live/upcoming': typeof DashboardLiveUpcomingRoute
  '/dashboard/open-verses/$genre': typeof DashboardOpenVersesGenreRouteWithChildren
  '/dashboard/open-verses/new': typeof DashboardOpenVersesNewRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/tracks/new': typeof DashboardTracksNewRoute
  '/dashboard/videos/new': typeof DashboardVideosNewRoute
  '/signup/artist/credentials': typeof SignupArtistCredentialsRoute
  '/signup/artist/onboarding': typeof SignupArtistOnboardingRoute
  '/signup/fan/credentials': typeof SignupFanCredentialsRoute
  '/signup/fan/onboarding': typeof SignupFanOnboardingRoute
  '/artist/': typeof ExploreArtistIndexRoute
  '/communities/': typeof ExploreCommunitiesIndexRoute
  '/genres/': typeof ExploreGenresIndexRoute
  '/library/': typeof ExploreLibraryIndexRoute
  '/live/': typeof ExploreLiveIndexRoute
  '/tracks/': typeof ExploreTracksIndexRoute
  '/videos/': typeof ExploreVideosIndexRoute
  '/dashboard/live/': typeof DashboardLiveIndexRoute
  '/dashboard/open-verses/': typeof DashboardOpenVersesIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/tracks/': typeof DashboardTracksIndexRoute
  '/dashboard/videos/': typeof DashboardVideosIndexRoute
  '/live/battles/$id': typeof ExploreLiveBattlesIdRoute
  '/live/battles/leaderboard': typeof ExploreLiveBattlesLeaderboardRoute
  '/live/battles/must-see': typeof ExploreLiveBattlesMustSeeRoute
  '/live/battles/upcoming': typeof ExploreLiveBattlesUpcomingRoute
  '/live/parties/$id': typeof ExploreLivePartiesIdRoute
  '/live/streams/$id': typeof ExploreLiveStreamsIdRoute
  '/dashboard/open-verses/$genre/$id': typeof DashboardOpenVersesGenreIdRoute
  '/dashboard/tracks/$id/edit': typeof DashboardTracksIdEditRoute
  '/library/playlists/': typeof ExploreLibraryPlaylistsIndexRoute
  '/library/purchased/': typeof ExploreLibraryPurchasedIndexRoute
  '/library/recent/': typeof ExploreLibraryRecentIndexRoute
  '/library/saved/': typeof ExploreLibrarySavedIndexRoute
  '/library/watched/': typeof ExploreLibraryWatchedIndexRoute
  '/live/battles/': typeof ExploreLiveBattlesIndexRoute
  '/live/parties/': typeof ExploreLivePartiesIndexRoute
  '/live/streams/': typeof ExploreLiveStreamsIndexRoute
  '/dashboard/live/my-stats/': typeof DashboardLiveMyStatsIndexRoute
  '/dashboard/tracks/$id/': typeof DashboardTracksIdIndexRoute
  '/library/playlists/$id/': typeof ExploreLibraryPlaylistsIdIndexRoute
}
export interface FileRoutesByTo {
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/new-releases': typeof ExploreNewReleasesRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/collaborators': typeof DashboardCollaboratorsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/music': typeof DashboardMusicRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/': typeof ExploreIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/artist/$username': typeof ExploreArtistUsernameRoute
  '/artist/new': typeof ExploreArtistNewRoute
  '/artist/rising-stars': typeof ExploreArtistRisingStarsRoute
  '/artist/top': typeof ExploreArtistTopRoute
  '/genres/$id': typeof ExploreGenresIdRoute
  '/library/settings': typeof ExploreLibrarySettingsRoute
  '/projects/$id': typeof ExploreProjectsIdRoute
  '/tracks/$id': typeof ExploreTracksIdRoute
  '/videos/$id': typeof ExploreVideosIdRoute
  '/dashboard/career/ai-studio': typeof DashboardCareerAiStudioRoute
  '/dashboard/career/analytics': typeof DashboardCareerAnalyticsRoute
  '/dashboard/career/calendar': typeof DashboardCareerCalendarRoute
  '/dashboard/career/profile': typeof DashboardCareerProfileRoute
  '/dashboard/career/settings': typeof DashboardCareerSettingsRoute
  '/dashboard/live/challenge': typeof DashboardLiveChallengeRoute
  '/dashboard/live/find': typeof DashboardLiveFindRoute
  '/dashboard/live/my-kit': typeof DashboardLiveMyKitRoute
  '/dashboard/live/parties': typeof DashboardLivePartiesRoute
  '/dashboard/live/streams': typeof DashboardLiveStreamsRoute
  '/dashboard/live/upcoming': typeof DashboardLiveUpcomingRoute
  '/dashboard/open-verses/$genre': typeof DashboardOpenVersesGenreRouteWithChildren
  '/dashboard/open-verses/new': typeof DashboardOpenVersesNewRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/tracks/new': typeof DashboardTracksNewRoute
  '/dashboard/videos/new': typeof DashboardVideosNewRoute
  '/signup/artist/credentials': typeof SignupArtistCredentialsRoute
  '/signup/artist/onboarding': typeof SignupArtistOnboardingRoute
  '/signup/fan/credentials': typeof SignupFanCredentialsRoute
  '/signup/fan/onboarding': typeof SignupFanOnboardingRoute
  '/artist': typeof ExploreArtistIndexRoute
  '/communities': typeof ExploreCommunitiesIndexRoute
  '/genres': typeof ExploreGenresIndexRoute
  '/library': typeof ExploreLibraryIndexRoute
  '/live': typeof ExploreLiveIndexRoute
  '/tracks': typeof ExploreTracksIndexRoute
  '/videos': typeof ExploreVideosIndexRoute
  '/dashboard/live': typeof DashboardLiveIndexRoute
  '/dashboard/open-verses': typeof DashboardOpenVersesIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/tracks': typeof DashboardTracksIndexRoute
  '/dashboard/videos': typeof DashboardVideosIndexRoute
  '/live/battles/$id': typeof ExploreLiveBattlesIdRoute
  '/live/battles/leaderboard': typeof ExploreLiveBattlesLeaderboardRoute
  '/live/battles/must-see': typeof ExploreLiveBattlesMustSeeRoute
  '/live/battles/upcoming': typeof ExploreLiveBattlesUpcomingRoute
  '/live/parties/$id': typeof ExploreLivePartiesIdRoute
  '/live/streams/$id': typeof ExploreLiveStreamsIdRoute
  '/dashboard/open-verses/$genre/$id': typeof DashboardOpenVersesGenreIdRoute
  '/dashboard/tracks/$id/edit': typeof DashboardTracksIdEditRoute
  '/library/playlists': typeof ExploreLibraryPlaylistsIndexRoute
  '/library/purchased': typeof ExploreLibraryPurchasedIndexRoute
  '/library/recent': typeof ExploreLibraryRecentIndexRoute
  '/library/saved': typeof ExploreLibrarySavedIndexRoute
  '/library/watched': typeof ExploreLibraryWatchedIndexRoute
  '/live/battles': typeof ExploreLiveBattlesIndexRoute
  '/live/parties': typeof ExploreLivePartiesIndexRoute
  '/live/streams': typeof ExploreLiveStreamsIndexRoute
  '/dashboard/live/my-stats': typeof DashboardLiveMyStatsIndexRoute
  '/dashboard/tracks/$id': typeof DashboardTracksIdIndexRoute
  '/library/playlists/$id': typeof ExploreLibraryPlaylistsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_explore': typeof ExploreRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_explore/live': typeof ExploreLiveRouteWithChildren
  '/_explore/new-releases': typeof ExploreNewReleasesRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/collaborators': typeof DashboardCollaboratorsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/music': typeof DashboardMusicRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/_explore/': typeof ExploreIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_explore/artist/$username': typeof ExploreArtistUsernameRoute
  '/_explore/artist/new': typeof ExploreArtistNewRoute
  '/_explore/artist/rising-stars': typeof ExploreArtistRisingStarsRoute
  '/_explore/artist/top': typeof ExploreArtistTopRoute
  '/_explore/genres/$id': typeof ExploreGenresIdRoute
  '/_explore/library/settings': typeof ExploreLibrarySettingsRoute
  '/_explore/projects/$id': typeof ExploreProjectsIdRoute
  '/_explore/tracks/$id': typeof ExploreTracksIdRoute
  '/_explore/videos/$id': typeof ExploreVideosIdRoute
  '/dashboard/career/ai-studio': typeof DashboardCareerAiStudioRoute
  '/dashboard/career/analytics': typeof DashboardCareerAnalyticsRoute
  '/dashboard/career/calendar': typeof DashboardCareerCalendarRoute
  '/dashboard/career/profile': typeof DashboardCareerProfileRoute
  '/dashboard/career/settings': typeof DashboardCareerSettingsRoute
  '/dashboard/live/challenge': typeof DashboardLiveChallengeRoute
  '/dashboard/live/find': typeof DashboardLiveFindRoute
  '/dashboard/live/my-kit': typeof DashboardLiveMyKitRoute
  '/dashboard/live/parties': typeof DashboardLivePartiesRoute
  '/dashboard/live/streams': typeof DashboardLiveStreamsRoute
  '/dashboard/live/upcoming': typeof DashboardLiveUpcomingRoute
  '/dashboard/open-verses/$genre': typeof DashboardOpenVersesGenreRouteWithChildren
  '/dashboard/open-verses/new': typeof DashboardOpenVersesNewRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/tracks/new': typeof DashboardTracksNewRoute
  '/dashboard/videos/new': typeof DashboardVideosNewRoute
  '/signup/artist/credentials': typeof SignupArtistCredentialsRoute
  '/signup/artist/onboarding': typeof SignupArtistOnboardingRoute
  '/signup/fan/credentials': typeof SignupFanCredentialsRoute
  '/signup/fan/onboarding': typeof SignupFanOnboardingRoute
  '/_explore/artist/': typeof ExploreArtistIndexRoute
  '/_explore/communities/': typeof ExploreCommunitiesIndexRoute
  '/_explore/genres/': typeof ExploreGenresIndexRoute
  '/_explore/library/': typeof ExploreLibraryIndexRoute
  '/_explore/live/': typeof ExploreLiveIndexRoute
  '/_explore/tracks/': typeof ExploreTracksIndexRoute
  '/_explore/videos/': typeof ExploreVideosIndexRoute
  '/dashboard/live/': typeof DashboardLiveIndexRoute
  '/dashboard/open-verses/': typeof DashboardOpenVersesIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/tracks/': typeof DashboardTracksIndexRoute
  '/dashboard/videos/': typeof DashboardVideosIndexRoute
  '/_explore/live/battles/$id': typeof ExploreLiveBattlesIdRoute
  '/_explore/live/battles/leaderboard': typeof ExploreLiveBattlesLeaderboardRoute
  '/_explore/live/battles/must-see': typeof ExploreLiveBattlesMustSeeRoute
  '/_explore/live/battles/upcoming': typeof ExploreLiveBattlesUpcomingRoute
  '/_explore/live/parties/$id': typeof ExploreLivePartiesIdRoute
  '/_explore/live/streams/$id': typeof ExploreLiveStreamsIdRoute
  '/dashboard/open-verses/$genre/$id': typeof DashboardOpenVersesGenreIdRoute
  '/dashboard/tracks/$id/edit': typeof DashboardTracksIdEditRoute
  '/_explore/library/playlists/': typeof ExploreLibraryPlaylistsIndexRoute
  '/_explore/library/purchased/': typeof ExploreLibraryPurchasedIndexRoute
  '/_explore/library/recent/': typeof ExploreLibraryRecentIndexRoute
  '/_explore/library/saved/': typeof ExploreLibrarySavedIndexRoute
  '/_explore/library/watched/': typeof ExploreLibraryWatchedIndexRoute
  '/_explore/live/battles/': typeof ExploreLiveBattlesIndexRoute
  '/_explore/live/parties/': typeof ExploreLivePartiesIndexRoute
  '/_explore/live/streams/': typeof ExploreLiveStreamsIndexRoute
  '/dashboard/live/my-stats/': typeof DashboardLiveMyStatsIndexRoute
  '/dashboard/tracks/$id/': typeof DashboardTracksIdIndexRoute
  '/_explore/library/playlists/$id/': typeof ExploreLibraryPlaylistsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/llms.txt'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/sitemap.xml'
    | '/live'
    | '/new-releases'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/collaborators'
    | '/dashboard/community'
    | '/dashboard/finance'
    | '/dashboard/messages'
    | '/dashboard/music'
    | '/dashboard/profile'
    | '/dashboard/team'
    | '/dashboard/'
    | '/artist/$username'
    | '/artist/new'
    | '/artist/rising-stars'
    | '/artist/top'
    | '/genres/$id'
    | '/library/settings'
    | '/projects/$id'
    | '/tracks/$id'
    | '/videos/$id'
    | '/dashboard/career/ai-studio'
    | '/dashboard/career/analytics'
    | '/dashboard/career/calendar'
    | '/dashboard/career/profile'
    | '/dashboard/career/settings'
    | '/dashboard/live/challenge'
    | '/dashboard/live/find'
    | '/dashboard/live/my-kit'
    | '/dashboard/live/parties'
    | '/dashboard/live/streams'
    | '/dashboard/live/upcoming'
    | '/dashboard/open-verses/$genre'
    | '/dashboard/open-verses/new'
    | '/dashboard/projects/$id'
    | '/dashboard/projects/new'
    | '/dashboard/tracks/new'
    | '/dashboard/videos/new'
    | '/signup/artist/credentials'
    | '/signup/artist/onboarding'
    | '/signup/fan/credentials'
    | '/signup/fan/onboarding'
    | '/artist/'
    | '/communities/'
    | '/genres/'
    | '/library/'
    | '/live/'
    | '/tracks/'
    | '/videos/'
    | '/dashboard/live/'
    | '/dashboard/open-verses/'
    | '/dashboard/projects/'
    | '/dashboard/tracks/'
    | '/dashboard/videos/'
    | '/live/battles/$id'
    | '/live/battles/leaderboard'
    | '/live/battles/must-see'
    | '/live/battles/upcoming'
    | '/live/parties/$id'
    | '/live/streams/$id'
    | '/dashboard/open-verses/$genre/$id'
    | '/dashboard/tracks/$id/edit'
    | '/library/playlists/'
    | '/library/purchased/'
    | '/library/recent/'
    | '/library/saved/'
    | '/library/watched/'
    | '/live/battles/'
    | '/live/parties/'
    | '/live/streams/'
    | '/dashboard/live/my-stats/'
    | '/dashboard/tracks/$id/'
    | '/library/playlists/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/llms.txt'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/sitemap.xml'
    | '/new-releases'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/collaborators'
    | '/dashboard/community'
    | '/dashboard/finance'
    | '/dashboard/messages'
    | '/dashboard/music'
    | '/dashboard/profile'
    | '/dashboard/team'
    | '/'
    | '/dashboard'
    | '/artist/$username'
    | '/artist/new'
    | '/artist/rising-stars'
    | '/artist/top'
    | '/genres/$id'
    | '/library/settings'
    | '/projects/$id'
    | '/tracks/$id'
    | '/videos/$id'
    | '/dashboard/career/ai-studio'
    | '/dashboard/career/analytics'
    | '/dashboard/career/calendar'
    | '/dashboard/career/profile'
    | '/dashboard/career/settings'
    | '/dashboard/live/challenge'
    | '/dashboard/live/find'
    | '/dashboard/live/my-kit'
    | '/dashboard/live/parties'
    | '/dashboard/live/streams'
    | '/dashboard/live/upcoming'
    | '/dashboard/open-verses/$genre'
    | '/dashboard/open-verses/new'
    | '/dashboard/projects/$id'
    | '/dashboard/projects/new'
    | '/dashboard/tracks/new'
    | '/dashboard/videos/new'
    | '/signup/artist/credentials'
    | '/signup/artist/onboarding'
    | '/signup/fan/credentials'
    | '/signup/fan/onboarding'
    | '/artist'
    | '/communities'
    | '/genres'
    | '/library'
    | '/live'
    | '/tracks'
    | '/videos'
    | '/dashboard/live'
    | '/dashboard/open-verses'
    | '/dashboard/projects'
    | '/dashboard/tracks'
    | '/dashboard/videos'
    | '/live/battles/$id'
    | '/live/battles/leaderboard'
    | '/live/battles/must-see'
    | '/live/battles/upcoming'
    | '/live/parties/$id'
    | '/live/streams/$id'
    | '/dashboard/open-verses/$genre/$id'
    | '/dashboard/tracks/$id/edit'
    | '/library/playlists'
    | '/library/purchased'
    | '/library/recent'
    | '/library/saved'
    | '/library/watched'
    | '/live/battles'
    | '/live/parties'
    | '/live/streams'
    | '/dashboard/live/my-stats'
    | '/dashboard/tracks/$id'
    | '/library/playlists/$id'
  id:
    | '__root__'
    | '/_explore'
    | '/dashboard'
    | '/llms.txt'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/sitemap.xml'
    | '/_explore/live'
    | '/_explore/new-releases'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/collaborators'
    | '/dashboard/community'
    | '/dashboard/finance'
    | '/dashboard/messages'
    | '/dashboard/music'
    | '/dashboard/profile'
    | '/dashboard/team'
    | '/_explore/'
    | '/dashboard/'
    | '/_explore/artist/$username'
    | '/_explore/artist/new'
    | '/_explore/artist/rising-stars'
    | '/_explore/artist/top'
    | '/_explore/genres/$id'
    | '/_explore/library/settings'
    | '/_explore/projects/$id'
    | '/_explore/tracks/$id'
    | '/_explore/videos/$id'
    | '/dashboard/career/ai-studio'
    | '/dashboard/career/analytics'
    | '/dashboard/career/calendar'
    | '/dashboard/career/profile'
    | '/dashboard/career/settings'
    | '/dashboard/live/challenge'
    | '/dashboard/live/find'
    | '/dashboard/live/my-kit'
    | '/dashboard/live/parties'
    | '/dashboard/live/streams'
    | '/dashboard/live/upcoming'
    | '/dashboard/open-verses/$genre'
    | '/dashboard/open-verses/new'
    | '/dashboard/projects/$id'
    | '/dashboard/projects/new'
    | '/dashboard/tracks/new'
    | '/dashboard/videos/new'
    | '/signup/artist/credentials'
    | '/signup/artist/onboarding'
    | '/signup/fan/credentials'
    | '/signup/fan/onboarding'
    | '/_explore/artist/'
    | '/_explore/communities/'
    | '/_explore/genres/'
    | '/_explore/library/'
    | '/_explore/live/'
    | '/_explore/tracks/'
    | '/_explore/videos/'
    | '/dashboard/live/'
    | '/dashboard/open-verses/'
    | '/dashboard/projects/'
    | '/dashboard/tracks/'
    | '/dashboard/videos/'
    | '/_explore/live/battles/$id'
    | '/_explore/live/battles/leaderboard'
    | '/_explore/live/battles/must-see'
    | '/_explore/live/battles/upcoming'
    | '/_explore/live/parties/$id'
    | '/_explore/live/streams/$id'
    | '/dashboard/open-verses/$genre/$id'
    | '/dashboard/tracks/$id/edit'
    | '/_explore/library/playlists/'
    | '/_explore/library/purchased/'
    | '/_explore/library/recent/'
    | '/_explore/library/saved/'
    | '/_explore/library/watched/'
    | '/_explore/live/battles/'
    | '/_explore/live/parties/'
    | '/_explore/live/streams/'
    | '/dashboard/live/my-stats/'
    | '/dashboard/tracks/$id/'
    | '/_explore/library/playlists/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ExploreRoute: typeof ExploreRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_explore': {
      id: '/_explore'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_explore/': {
      id: '/_explore/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/music': {
      id: '/dashboard/music'
      path: '/music'
      fullPath: '/dashboard/music'
      preLoaderRoute: typeof DashboardMusicRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/finance': {
      id: '/dashboard/finance'
      path: '/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof DashboardFinanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/community': {
      id: '/dashboard/community'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof DashboardCommunityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/collaborators': {
      id: '/dashboard/collaborators'
      path: '/collaborators'
      fullPath: '/dashboard/collaborators'
      preLoaderRoute: typeof DashboardCollaboratorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_explore/new-releases': {
      id: '/_explore/new-releases'
      path: '/new-releases'
      fullPath: '/new-releases'
      preLoaderRoute: typeof ExploreNewReleasesRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/live': {
      id: '/_explore/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof ExploreLiveRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/dashboard/videos/': {
      id: '/dashboard/videos/'
      path: '/videos'
      fullPath: '/dashboard/videos/'
      preLoaderRoute: typeof DashboardVideosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tracks/': {
      id: '/dashboard/tracks/'
      path: '/tracks'
      fullPath: '/dashboard/tracks/'
      preLoaderRoute: typeof DashboardTracksIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/open-verses/': {
      id: '/dashboard/open-verses/'
      path: '/open-verses'
      fullPath: '/dashboard/open-verses/'
      preLoaderRoute: typeof DashboardOpenVersesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live/': {
      id: '/dashboard/live/'
      path: '/live'
      fullPath: '/dashboard/live/'
      preLoaderRoute: typeof DashboardLiveIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_explore/videos/': {
      id: '/_explore/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof ExploreVideosIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/tracks/': {
      id: '/_explore/tracks/'
      path: '/tracks'
      fullPath: '/tracks/'
      preLoaderRoute: typeof ExploreTracksIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/live/': {
      id: '/_explore/live/'
      path: '/'
      fullPath: '/live/'
      preLoaderRoute: typeof ExploreLiveIndexRouteImport
      parentRoute: typeof ExploreLiveRoute
    }
    '/_explore/library/': {
      id: '/_explore/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof ExploreLibraryIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/genres/': {
      id: '/_explore/genres/'
      path: '/genres'
      fullPath: '/genres/'
      preLoaderRoute: typeof ExploreGenresIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/communities/': {
      id: '/_explore/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof ExploreCommunitiesIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/artist/': {
      id: '/_explore/artist/'
      path: '/artist'
      fullPath: '/artist/'
      preLoaderRoute: typeof ExploreArtistIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/signup/fan/onboarding': {
      id: '/signup/fan/onboarding'
      path: '/fan/onboarding'
      fullPath: '/signup/fan/onboarding'
      preLoaderRoute: typeof SignupFanOnboardingRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/fan/credentials': {
      id: '/signup/fan/credentials'
      path: '/fan/credentials'
      fullPath: '/signup/fan/credentials'
      preLoaderRoute: typeof SignupFanCredentialsRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/artist/onboarding': {
      id: '/signup/artist/onboarding'
      path: '/artist/onboarding'
      fullPath: '/signup/artist/onboarding'
      preLoaderRoute: typeof SignupArtistOnboardingRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/artist/credentials': {
      id: '/signup/artist/credentials'
      path: '/artist/credentials'
      fullPath: '/signup/artist/credentials'
      preLoaderRoute: typeof SignupArtistCredentialsRouteImport
      parentRoute: typeof SignupRoute
    }
    '/dashboard/videos/new': {
      id: '/dashboard/videos/new'
      path: '/videos/new'
      fullPath: '/dashboard/videos/new'
      preLoaderRoute: typeof DashboardVideosNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tracks/new': {
      id: '/dashboard/tracks/new'
      path: '/tracks/new'
      fullPath: '/dashboard/tracks/new'
      preLoaderRoute: typeof DashboardTracksNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/new': {
      id: '/dashboard/projects/new'
      path: '/projects/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$id': {
      id: '/dashboard/projects/$id'
      path: '/projects/$id'
      fullPath: '/dashboard/projects/$id'
      preLoaderRoute: typeof DashboardProjectsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/open-verses/new': {
      id: '/dashboard/open-verses/new'
      path: '/open-verses/new'
      fullPath: '/dashboard/open-verses/new'
      preLoaderRoute: typeof DashboardOpenVersesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/open-verses/$genre': {
      id: '/dashboard/open-verses/$genre'
      path: '/open-verses/$genre'
      fullPath: '/dashboard/open-verses/$genre'
      preLoaderRoute: typeof DashboardOpenVersesGenreRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live/upcoming': {
      id: '/dashboard/live/upcoming'
      path: '/live/upcoming'
      fullPath: '/dashboard/live/upcoming'
      preLoaderRoute: typeof DashboardLiveUpcomingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live/streams': {
      id: '/dashboard/live/streams'
      path: '/live/streams'
      fullPath: '/dashboard/live/streams'
      preLoaderRoute: typeof DashboardLiveStreamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live/parties': {
      id: '/dashboard/live/parties'
      path: '/live/parties'
      fullPath: '/dashboard/live/parties'
      preLoaderRoute: typeof DashboardLivePartiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live/my-kit': {
      id: '/dashboard/live/my-kit'
      path: '/live/my-kit'
      fullPath: '/dashboard/live/my-kit'
      preLoaderRoute: typeof DashboardLiveMyKitRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live/find': {
      id: '/dashboard/live/find'
      path: '/live/find'
      fullPath: '/dashboard/live/find'
      preLoaderRoute: typeof DashboardLiveFindRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live/challenge': {
      id: '/dashboard/live/challenge'
      path: '/live/challenge'
      fullPath: '/dashboard/live/challenge'
      preLoaderRoute: typeof DashboardLiveChallengeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/career/settings': {
      id: '/dashboard/career/settings'
      path: '/career/settings'
      fullPath: '/dashboard/career/settings'
      preLoaderRoute: typeof DashboardCareerSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/career/profile': {
      id: '/dashboard/career/profile'
      path: '/career/profile'
      fullPath: '/dashboard/career/profile'
      preLoaderRoute: typeof DashboardCareerProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/career/calendar': {
      id: '/dashboard/career/calendar'
      path: '/career/calendar'
      fullPath: '/dashboard/career/calendar'
      preLoaderRoute: typeof DashboardCareerCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/career/analytics': {
      id: '/dashboard/career/analytics'
      path: '/career/analytics'
      fullPath: '/dashboard/career/analytics'
      preLoaderRoute: typeof DashboardCareerAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/career/ai-studio': {
      id: '/dashboard/career/ai-studio'
      path: '/career/ai-studio'
      fullPath: '/dashboard/career/ai-studio'
      preLoaderRoute: typeof DashboardCareerAiStudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_explore/videos/$id': {
      id: '/_explore/videos/$id'
      path: '/videos/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof ExploreVideosIdRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/tracks/$id': {
      id: '/_explore/tracks/$id'
      path: '/tracks/$id'
      fullPath: '/tracks/$id'
      preLoaderRoute: typeof ExploreTracksIdRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/projects/$id': {
      id: '/_explore/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ExploreProjectsIdRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/library/settings': {
      id: '/_explore/library/settings'
      path: '/library/settings'
      fullPath: '/library/settings'
      preLoaderRoute: typeof ExploreLibrarySettingsRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/genres/$id': {
      id: '/_explore/genres/$id'
      path: '/genres/$id'
      fullPath: '/genres/$id'
      preLoaderRoute: typeof ExploreGenresIdRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/artist/top': {
      id: '/_explore/artist/top'
      path: '/artist/top'
      fullPath: '/artist/top'
      preLoaderRoute: typeof ExploreArtistTopRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/artist/rising-stars': {
      id: '/_explore/artist/rising-stars'
      path: '/artist/rising-stars'
      fullPath: '/artist/rising-stars'
      preLoaderRoute: typeof ExploreArtistRisingStarsRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/artist/new': {
      id: '/_explore/artist/new'
      path: '/artist/new'
      fullPath: '/artist/new'
      preLoaderRoute: typeof ExploreArtistNewRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/artist/$username': {
      id: '/_explore/artist/$username'
      path: '/artist/$username'
      fullPath: '/artist/$username'
      preLoaderRoute: typeof ExploreArtistUsernameRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/dashboard/tracks/$id/': {
      id: '/dashboard/tracks/$id/'
      path: '/tracks/$id'
      fullPath: '/dashboard/tracks/$id/'
      preLoaderRoute: typeof DashboardTracksIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live/my-stats/': {
      id: '/dashboard/live/my-stats/'
      path: '/live/my-stats'
      fullPath: '/dashboard/live/my-stats/'
      preLoaderRoute: typeof DashboardLiveMyStatsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_explore/live/streams/': {
      id: '/_explore/live/streams/'
      path: '/streams'
      fullPath: '/live/streams/'
      preLoaderRoute: typeof ExploreLiveStreamsIndexRouteImport
      parentRoute: typeof ExploreLiveRoute
    }
    '/_explore/live/parties/': {
      id: '/_explore/live/parties/'
      path: '/parties'
      fullPath: '/live/parties/'
      preLoaderRoute: typeof ExploreLivePartiesIndexRouteImport
      parentRoute: typeof ExploreLiveRoute
    }
    '/_explore/live/battles/': {
      id: '/_explore/live/battles/'
      path: '/battles'
      fullPath: '/live/battles/'
      preLoaderRoute: typeof ExploreLiveBattlesIndexRouteImport
      parentRoute: typeof ExploreLiveRoute
    }
    '/_explore/library/watched/': {
      id: '/_explore/library/watched/'
      path: '/library/watched'
      fullPath: '/library/watched/'
      preLoaderRoute: typeof ExploreLibraryWatchedIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/library/saved/': {
      id: '/_explore/library/saved/'
      path: '/library/saved'
      fullPath: '/library/saved/'
      preLoaderRoute: typeof ExploreLibrarySavedIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/library/recent/': {
      id: '/_explore/library/recent/'
      path: '/library/recent'
      fullPath: '/library/recent/'
      preLoaderRoute: typeof ExploreLibraryRecentIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/library/purchased/': {
      id: '/_explore/library/purchased/'
      path: '/library/purchased'
      fullPath: '/library/purchased/'
      preLoaderRoute: typeof ExploreLibraryPurchasedIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/library/playlists/': {
      id: '/_explore/library/playlists/'
      path: '/library/playlists'
      fullPath: '/library/playlists/'
      preLoaderRoute: typeof ExploreLibraryPlaylistsIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/dashboard/tracks/$id/edit': {
      id: '/dashboard/tracks/$id/edit'
      path: '/tracks/$id/edit'
      fullPath: '/dashboard/tracks/$id/edit'
      preLoaderRoute: typeof DashboardTracksIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/open-verses/$genre/$id': {
      id: '/dashboard/open-verses/$genre/$id'
      path: '/$id'
      fullPath: '/dashboard/open-verses/$genre/$id'
      preLoaderRoute: typeof DashboardOpenVersesGenreIdRouteImport
      parentRoute: typeof DashboardOpenVersesGenreRoute
    }
    '/_explore/live/streams/$id': {
      id: '/_explore/live/streams/$id'
      path: '/streams/$id'
      fullPath: '/live/streams/$id'
      preLoaderRoute: typeof ExploreLiveStreamsIdRouteImport
      parentRoute: typeof ExploreLiveRoute
    }
    '/_explore/live/parties/$id': {
      id: '/_explore/live/parties/$id'
      path: '/parties/$id'
      fullPath: '/live/parties/$id'
      preLoaderRoute: typeof ExploreLivePartiesIdRouteImport
      parentRoute: typeof ExploreLiveRoute
    }
    '/_explore/live/battles/upcoming': {
      id: '/_explore/live/battles/upcoming'
      path: '/battles/upcoming'
      fullPath: '/live/battles/upcoming'
      preLoaderRoute: typeof ExploreLiveBattlesUpcomingRouteImport
      parentRoute: typeof ExploreLiveRoute
    }
    '/_explore/live/battles/must-see': {
      id: '/_explore/live/battles/must-see'
      path: '/battles/must-see'
      fullPath: '/live/battles/must-see'
      preLoaderRoute: typeof ExploreLiveBattlesMustSeeRouteImport
      parentRoute: typeof ExploreLiveRoute
    }
    '/_explore/live/battles/leaderboard': {
      id: '/_explore/live/battles/leaderboard'
      path: '/battles/leaderboard'
      fullPath: '/live/battles/leaderboard'
      preLoaderRoute: typeof ExploreLiveBattlesLeaderboardRouteImport
      parentRoute: typeof ExploreLiveRoute
    }
    '/_explore/live/battles/$id': {
      id: '/_explore/live/battles/$id'
      path: '/battles/$id'
      fullPath: '/live/battles/$id'
      preLoaderRoute: typeof ExploreLiveBattlesIdRouteImport
      parentRoute: typeof ExploreLiveRoute
    }
    '/_explore/library/playlists/$id/': {
      id: '/_explore/library/playlists/$id/'
      path: '/library/playlists/$id'
      fullPath: '/library/playlists/$id/'
      preLoaderRoute: typeof ExploreLibraryPlaylistsIdIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
  }
}

interface ExploreLiveRouteChildren {
  ExploreLiveIndexRoute: typeof ExploreLiveIndexRoute
  ExploreLiveBattlesIdRoute: typeof ExploreLiveBattlesIdRoute
  ExploreLiveBattlesLeaderboardRoute: typeof ExploreLiveBattlesLeaderboardRoute
  ExploreLiveBattlesMustSeeRoute: typeof ExploreLiveBattlesMustSeeRoute
  ExploreLiveBattlesUpcomingRoute: typeof ExploreLiveBattlesUpcomingRoute
  ExploreLivePartiesIdRoute: typeof ExploreLivePartiesIdRoute
  ExploreLiveStreamsIdRoute: typeof ExploreLiveStreamsIdRoute
  ExploreLiveBattlesIndexRoute: typeof ExploreLiveBattlesIndexRoute
  ExploreLivePartiesIndexRoute: typeof ExploreLivePartiesIndexRoute
  ExploreLiveStreamsIndexRoute: typeof ExploreLiveStreamsIndexRoute
}

const ExploreLiveRouteChildren: ExploreLiveRouteChildren = {
  ExploreLiveIndexRoute: ExploreLiveIndexRoute,
  ExploreLiveBattlesIdRoute: ExploreLiveBattlesIdRoute,
  ExploreLiveBattlesLeaderboardRoute: ExploreLiveBattlesLeaderboardRoute,
  ExploreLiveBattlesMustSeeRoute: ExploreLiveBattlesMustSeeRoute,
  ExploreLiveBattlesUpcomingRoute: ExploreLiveBattlesUpcomingRoute,
  ExploreLivePartiesIdRoute: ExploreLivePartiesIdRoute,
  ExploreLiveStreamsIdRoute: ExploreLiveStreamsIdRoute,
  ExploreLiveBattlesIndexRoute: ExploreLiveBattlesIndexRoute,
  ExploreLivePartiesIndexRoute: ExploreLivePartiesIndexRoute,
  ExploreLiveStreamsIndexRoute: ExploreLiveStreamsIndexRoute,
}

const ExploreLiveRouteWithChildren = ExploreLiveRoute._addFileChildren(
  ExploreLiveRouteChildren,
)

interface ExploreRouteChildren {
  ExploreLiveRoute: typeof ExploreLiveRouteWithChildren
  ExploreNewReleasesRoute: typeof ExploreNewReleasesRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  ExploreArtistUsernameRoute: typeof ExploreArtistUsernameRoute
  ExploreArtistNewRoute: typeof ExploreArtistNewRoute
  ExploreArtistRisingStarsRoute: typeof ExploreArtistRisingStarsRoute
  ExploreArtistTopRoute: typeof ExploreArtistTopRoute
  ExploreGenresIdRoute: typeof ExploreGenresIdRoute
  ExploreLibrarySettingsRoute: typeof ExploreLibrarySettingsRoute
  ExploreProjectsIdRoute: typeof ExploreProjectsIdRoute
  ExploreTracksIdRoute: typeof ExploreTracksIdRoute
  ExploreVideosIdRoute: typeof ExploreVideosIdRoute
  ExploreArtistIndexRoute: typeof ExploreArtistIndexRoute
  ExploreCommunitiesIndexRoute: typeof ExploreCommunitiesIndexRoute
  ExploreGenresIndexRoute: typeof ExploreGenresIndexRoute
  ExploreLibraryIndexRoute: typeof ExploreLibraryIndexRoute
  ExploreTracksIndexRoute: typeof ExploreTracksIndexRoute
  ExploreVideosIndexRoute: typeof ExploreVideosIndexRoute
  ExploreLibraryPlaylistsIndexRoute: typeof ExploreLibraryPlaylistsIndexRoute
  ExploreLibraryPurchasedIndexRoute: typeof ExploreLibraryPurchasedIndexRoute
  ExploreLibraryRecentIndexRoute: typeof ExploreLibraryRecentIndexRoute
  ExploreLibrarySavedIndexRoute: typeof ExploreLibrarySavedIndexRoute
  ExploreLibraryWatchedIndexRoute: typeof ExploreLibraryWatchedIndexRoute
  ExploreLibraryPlaylistsIdIndexRoute: typeof ExploreLibraryPlaylistsIdIndexRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreLiveRoute: ExploreLiveRouteWithChildren,
  ExploreNewReleasesRoute: ExploreNewReleasesRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  ExploreArtistUsernameRoute: ExploreArtistUsernameRoute,
  ExploreArtistNewRoute: ExploreArtistNewRoute,
  ExploreArtistRisingStarsRoute: ExploreArtistRisingStarsRoute,
  ExploreArtistTopRoute: ExploreArtistTopRoute,
  ExploreGenresIdRoute: ExploreGenresIdRoute,
  ExploreLibrarySettingsRoute: ExploreLibrarySettingsRoute,
  ExploreProjectsIdRoute: ExploreProjectsIdRoute,
  ExploreTracksIdRoute: ExploreTracksIdRoute,
  ExploreVideosIdRoute: ExploreVideosIdRoute,
  ExploreArtistIndexRoute: ExploreArtistIndexRoute,
  ExploreCommunitiesIndexRoute: ExploreCommunitiesIndexRoute,
  ExploreGenresIndexRoute: ExploreGenresIndexRoute,
  ExploreLibraryIndexRoute: ExploreLibraryIndexRoute,
  ExploreTracksIndexRoute: ExploreTracksIndexRoute,
  ExploreVideosIndexRoute: ExploreVideosIndexRoute,
  ExploreLibraryPlaylistsIndexRoute: ExploreLibraryPlaylistsIndexRoute,
  ExploreLibraryPurchasedIndexRoute: ExploreLibraryPurchasedIndexRoute,
  ExploreLibraryRecentIndexRoute: ExploreLibraryRecentIndexRoute,
  ExploreLibrarySavedIndexRoute: ExploreLibrarySavedIndexRoute,
  ExploreLibraryWatchedIndexRoute: ExploreLibraryWatchedIndexRoute,
  ExploreLibraryPlaylistsIdIndexRoute: ExploreLibraryPlaylistsIdIndexRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface DashboardOpenVersesGenreRouteChildren {
  DashboardOpenVersesGenreIdRoute: typeof DashboardOpenVersesGenreIdRoute
}

const DashboardOpenVersesGenreRouteChildren: DashboardOpenVersesGenreRouteChildren =
  {
    DashboardOpenVersesGenreIdRoute: DashboardOpenVersesGenreIdRoute,
  }

const DashboardOpenVersesGenreRouteWithChildren =
  DashboardOpenVersesGenreRoute._addFileChildren(
    DashboardOpenVersesGenreRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCollaboratorsRoute: typeof DashboardCollaboratorsRoute
  DashboardCommunityRoute: typeof DashboardCommunityRoute
  DashboardFinanceRoute: typeof DashboardFinanceRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardMusicRoute: typeof DashboardMusicRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCareerAiStudioRoute: typeof DashboardCareerAiStudioRoute
  DashboardCareerAnalyticsRoute: typeof DashboardCareerAnalyticsRoute
  DashboardCareerCalendarRoute: typeof DashboardCareerCalendarRoute
  DashboardCareerProfileRoute: typeof DashboardCareerProfileRoute
  DashboardCareerSettingsRoute: typeof DashboardCareerSettingsRoute
  DashboardLiveChallengeRoute: typeof DashboardLiveChallengeRoute
  DashboardLiveFindRoute: typeof DashboardLiveFindRoute
  DashboardLiveMyKitRoute: typeof DashboardLiveMyKitRoute
  DashboardLivePartiesRoute: typeof DashboardLivePartiesRoute
  DashboardLiveStreamsRoute: typeof DashboardLiveStreamsRoute
  DashboardLiveUpcomingRoute: typeof DashboardLiveUpcomingRoute
  DashboardOpenVersesGenreRoute: typeof DashboardOpenVersesGenreRouteWithChildren
  DashboardOpenVersesNewRoute: typeof DashboardOpenVersesNewRoute
  DashboardProjectsIdRoute: typeof DashboardProjectsIdRoute
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
  DashboardTracksNewRoute: typeof DashboardTracksNewRoute
  DashboardVideosNewRoute: typeof DashboardVideosNewRoute
  DashboardLiveIndexRoute: typeof DashboardLiveIndexRoute
  DashboardOpenVersesIndexRoute: typeof DashboardOpenVersesIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardTracksIndexRoute: typeof DashboardTracksIndexRoute
  DashboardVideosIndexRoute: typeof DashboardVideosIndexRoute
  DashboardTracksIdEditRoute: typeof DashboardTracksIdEditRoute
  DashboardLiveMyStatsIndexRoute: typeof DashboardLiveMyStatsIndexRoute
  DashboardTracksIdIndexRoute: typeof DashboardTracksIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCollaboratorsRoute: DashboardCollaboratorsRoute,
  DashboardCommunityRoute: DashboardCommunityRoute,
  DashboardFinanceRoute: DashboardFinanceRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardMusicRoute: DashboardMusicRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCareerAiStudioRoute: DashboardCareerAiStudioRoute,
  DashboardCareerAnalyticsRoute: DashboardCareerAnalyticsRoute,
  DashboardCareerCalendarRoute: DashboardCareerCalendarRoute,
  DashboardCareerProfileRoute: DashboardCareerProfileRoute,
  DashboardCareerSettingsRoute: DashboardCareerSettingsRoute,
  DashboardLiveChallengeRoute: DashboardLiveChallengeRoute,
  DashboardLiveFindRoute: DashboardLiveFindRoute,
  DashboardLiveMyKitRoute: DashboardLiveMyKitRoute,
  DashboardLivePartiesRoute: DashboardLivePartiesRoute,
  DashboardLiveStreamsRoute: DashboardLiveStreamsRoute,
  DashboardLiveUpcomingRoute: DashboardLiveUpcomingRoute,
  DashboardOpenVersesGenreRoute: DashboardOpenVersesGenreRouteWithChildren,
  DashboardOpenVersesNewRoute: DashboardOpenVersesNewRoute,
  DashboardProjectsIdRoute: DashboardProjectsIdRoute,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
  DashboardTracksNewRoute: DashboardTracksNewRoute,
  DashboardVideosNewRoute: DashboardVideosNewRoute,
  DashboardLiveIndexRoute: DashboardLiveIndexRoute,
  DashboardOpenVersesIndexRoute: DashboardOpenVersesIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardTracksIndexRoute: DashboardTracksIndexRoute,
  DashboardVideosIndexRoute: DashboardVideosIndexRoute,
  DashboardTracksIdEditRoute: DashboardTracksIdEditRoute,
  DashboardLiveMyStatsIndexRoute: DashboardLiveMyStatsIndexRoute,
  DashboardTracksIdIndexRoute: DashboardTracksIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SignupRouteChildren {
  SignupArtistCredentialsRoute: typeof SignupArtistCredentialsRoute
  SignupArtistOnboardingRoute: typeof SignupArtistOnboardingRoute
  SignupFanCredentialsRoute: typeof SignupFanCredentialsRoute
  SignupFanOnboardingRoute: typeof SignupFanOnboardingRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupArtistCredentialsRoute: SignupArtistCredentialsRoute,
  SignupArtistOnboardingRoute: SignupArtistOnboardingRoute,
  SignupFanCredentialsRoute: SignupFanCredentialsRoute,
  SignupFanOnboardingRoute: SignupFanOnboardingRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ExploreRoute: ExploreRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
