/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as SignupRouteImport } from './app/signup'
import { Route as LoginRouteImport } from './app/login'
import { Route as DashboardRouteImport } from './app/dashboard'
import { Route as ExploreRouteImport } from './app/_explore'
import { Route as DashboardIndexRouteImport } from './app/dashboard/index'
import { Route as ExploreIndexRouteImport } from './app/_explore/index'
import { Route as DashboardTeamRouteImport } from './app/dashboard/team'
import { Route as DashboardProfileRouteImport } from './app/dashboard/profile'
import { Route as DashboardMusicRouteImport } from './app/dashboard/music'
import { Route as DashboardMessagesRouteImport } from './app/dashboard/messages'
import { Route as DashboardCollaboratorsRouteImport } from './app/dashboard/collaborators'
import { Route as ExploreNewReleasesRouteImport } from './app/_explore/new-releases'
import { Route as DashboardTracksIndexRouteImport } from './app/dashboard/tracks/index'
import { Route as DashboardProjectsIndexRouteImport } from './app/dashboard/projects/index'
import { Route as DashboardBattlesIndexRouteImport } from './app/dashboard/battles/index'
import { Route as ExploreTracksIndexRouteImport } from './app/_explore/tracks/index'
import { Route as ExploreLibraryIndexRouteImport } from './app/_explore/library/index'
import { Route as ExploreGenresIndexRouteImport } from './app/_explore/genres/index'
import { Route as ExploreBattlesIndexRouteImport } from './app/_explore/battles/index'
import { Route as ExploreArtistIndexRouteImport } from './app/_explore/artist/index'
import { Route as SignupFanOnboardingRouteImport } from './app/signup/fan/onboarding'
import { Route as SignupFanCredentialsRouteImport } from './app/signup/fan/credentials'
import { Route as SignupArtistOnboardingRouteImport } from './app/signup/artist/onboarding'
import { Route as SignupArtistCredentialsRouteImport } from './app/signup/artist/credentials'
import { Route as DashboardTracksNewRouteImport } from './app/dashboard/tracks/new'
import { Route as DashboardProjectsNewRouteImport } from './app/dashboard/projects/new'
import { Route as DashboardProjectsIdRouteImport } from './app/dashboard/projects/$id'
import { Route as DashboardCareerSettingsRouteImport } from './app/dashboard/career/settings'
import { Route as DashboardCareerProfileRouteImport } from './app/dashboard/career/profile'
import { Route as DashboardCareerAnalyticsRouteImport } from './app/dashboard/career/analytics'
import { Route as DashboardCareerAiStudioRouteImport } from './app/dashboard/career/ai-studio'
import { Route as DashboardBattlesUpcomingRouteImport } from './app/dashboard/battles/upcoming'
import { Route as DashboardBattlesMyKitRouteImport } from './app/dashboard/battles/my-kit'
import { Route as DashboardBattlesFindRouteImport } from './app/dashboard/battles/find'
import { Route as DashboardBattlesChallengeRouteImport } from './app/dashboard/battles/challenge'
import { Route as ExploreTracksIdRouteImport } from './app/_explore/tracks/$id'
import { Route as ExploreLibrarySettingsRouteImport } from './app/_explore/library/settings'
import { Route as ExploreGenresIdRouteImport } from './app/_explore/genres/$id'
import { Route as ExploreBattlesUpcomingRouteImport } from './app/_explore/battles/upcoming'
import { Route as ExploreBattlesMustSeeRouteImport } from './app/_explore/battles/must-see'
import { Route as ExploreBattlesLiveRouteImport } from './app/_explore/battles/live'
import { Route as ExploreBattlesLeaderboardRouteImport } from './app/_explore/battles/leaderboard'
import { Route as ExploreBattlesIdRouteImport } from './app/_explore/battles/$id'
import { Route as ExploreArtistTopRouteImport } from './app/_explore/artist/top'
import { Route as ExploreArtistRisingStarsRouteImport } from './app/_explore/artist/rising-stars'
import { Route as ExploreArtistNewRouteImport } from './app/_explore/artist/new'
import { Route as ExploreArtistUsernameRouteImport } from './app/_explore/artist/$username'
import { Route as DashboardTracksIdIndexRouteImport } from './app/dashboard/tracks/$id/index'
import { Route as DashboardBattlesMyStatsIndexRouteImport } from './app/dashboard/battles/my-stats/index'
import { Route as ExploreLibrarySavedIndexRouteImport } from './app/_explore/library/saved/index'
import { Route as ExploreLibraryRecentIndexRouteImport } from './app/_explore/library/recent/index'
import { Route as ExploreLibraryPurchasedIndexRouteImport } from './app/_explore/library/purchased/index'
import { Route as ExploreLibraryPlaylistsIndexRouteImport } from './app/_explore/library/playlists/index'
import { Route as DashboardTracksIdEditRouteImport } from './app/dashboard/tracks/$id/edit'
import { Route as ExploreLibraryPlaylistsIdIndexRouteImport } from './app/_explore/library/playlists/$id/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/_explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExploreRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMusicRoute = DashboardMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCollaboratorsRoute = DashboardCollaboratorsRouteImport.update({
  id: '/collaborators',
  path: '/collaborators',
  getParentRoute: () => DashboardRoute,
} as any)
const ExploreNewReleasesRoute = ExploreNewReleasesRouteImport.update({
  id: '/new-releases',
  path: '/new-releases',
  getParentRoute: () => ExploreRoute,
} as any)
const DashboardTracksIndexRoute = DashboardTracksIndexRouteImport.update({
  id: '/tracks/',
  path: '/tracks/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBattlesIndexRoute = DashboardBattlesIndexRouteImport.update({
  id: '/battles/',
  path: '/battles/',
  getParentRoute: () => DashboardRoute,
} as any)
const ExploreTracksIndexRoute = ExploreTracksIndexRouteImport.update({
  id: '/tracks/',
  path: '/tracks/',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreLibraryIndexRoute = ExploreLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreGenresIndexRoute = ExploreGenresIndexRouteImport.update({
  id: '/genres/',
  path: '/genres/',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreBattlesIndexRoute = ExploreBattlesIndexRouteImport.update({
  id: '/battles/',
  path: '/battles/',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreArtistIndexRoute = ExploreArtistIndexRouteImport.update({
  id: '/artist/',
  path: '/artist/',
  getParentRoute: () => ExploreRoute,
} as any)
const SignupFanOnboardingRoute = SignupFanOnboardingRouteImport.update({
  id: '/fan/onboarding',
  path: '/fan/onboarding',
  getParentRoute: () => SignupRoute,
} as any)
const SignupFanCredentialsRoute = SignupFanCredentialsRouteImport.update({
  id: '/fan/credentials',
  path: '/fan/credentials',
  getParentRoute: () => SignupRoute,
} as any)
const SignupArtistOnboardingRoute = SignupArtistOnboardingRouteImport.update({
  id: '/artist/onboarding',
  path: '/artist/onboarding',
  getParentRoute: () => SignupRoute,
} as any)
const SignupArtistCredentialsRoute = SignupArtistCredentialsRouteImport.update({
  id: '/artist/credentials',
  path: '/artist/credentials',
  getParentRoute: () => SignupRoute,
} as any)
const DashboardTracksNewRoute = DashboardTracksNewRouteImport.update({
  id: '/tracks/new',
  path: '/tracks/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIdRoute = DashboardProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCareerSettingsRoute = DashboardCareerSettingsRouteImport.update({
  id: '/career/settings',
  path: '/career/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCareerProfileRoute = DashboardCareerProfileRouteImport.update({
  id: '/career/profile',
  path: '/career/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCareerAnalyticsRoute =
  DashboardCareerAnalyticsRouteImport.update({
    id: '/career/analytics',
    path: '/career/analytics',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCareerAiStudioRoute = DashboardCareerAiStudioRouteImport.update({
  id: '/career/ai-studio',
  path: '/career/ai-studio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBattlesUpcomingRoute =
  DashboardBattlesUpcomingRouteImport.update({
    id: '/battles/upcoming',
    path: '/battles/upcoming',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBattlesMyKitRoute = DashboardBattlesMyKitRouteImport.update({
  id: '/battles/my-kit',
  path: '/battles/my-kit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBattlesFindRoute = DashboardBattlesFindRouteImport.update({
  id: '/battles/find',
  path: '/battles/find',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBattlesChallengeRoute =
  DashboardBattlesChallengeRouteImport.update({
    id: '/battles/challenge',
    path: '/battles/challenge',
    getParentRoute: () => DashboardRoute,
  } as any)
const ExploreTracksIdRoute = ExploreTracksIdRouteImport.update({
  id: '/tracks/$id',
  path: '/tracks/$id',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreLibrarySettingsRoute = ExploreLibrarySettingsRouteImport.update({
  id: '/library/settings',
  path: '/library/settings',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreGenresIdRoute = ExploreGenresIdRouteImport.update({
  id: '/genres/$id',
  path: '/genres/$id',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreBattlesUpcomingRoute = ExploreBattlesUpcomingRouteImport.update({
  id: '/battles/upcoming',
  path: '/battles/upcoming',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreBattlesMustSeeRoute = ExploreBattlesMustSeeRouteImport.update({
  id: '/battles/must-see',
  path: '/battles/must-see',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreBattlesLiveRoute = ExploreBattlesLiveRouteImport.update({
  id: '/battles/live',
  path: '/battles/live',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreBattlesLeaderboardRoute =
  ExploreBattlesLeaderboardRouteImport.update({
    id: '/battles/leaderboard',
    path: '/battles/leaderboard',
    getParentRoute: () => ExploreRoute,
  } as any)
const ExploreBattlesIdRoute = ExploreBattlesIdRouteImport.update({
  id: '/battles/$id',
  path: '/battles/$id',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreArtistTopRoute = ExploreArtistTopRouteImport.update({
  id: '/artist/top',
  path: '/artist/top',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreArtistRisingStarsRoute =
  ExploreArtistRisingStarsRouteImport.update({
    id: '/artist/rising-stars',
    path: '/artist/rising-stars',
    getParentRoute: () => ExploreRoute,
  } as any)
const ExploreArtistNewRoute = ExploreArtistNewRouteImport.update({
  id: '/artist/new',
  path: '/artist/new',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreArtistUsernameRoute = ExploreArtistUsernameRouteImport.update({
  id: '/artist/$username',
  path: '/artist/$username',
  getParentRoute: () => ExploreRoute,
} as any)
const DashboardTracksIdIndexRoute = DashboardTracksIdIndexRouteImport.update({
  id: '/tracks/$id/',
  path: '/tracks/$id/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBattlesMyStatsIndexRoute =
  DashboardBattlesMyStatsIndexRouteImport.update({
    id: '/battles/my-stats/',
    path: '/battles/my-stats/',
    getParentRoute: () => DashboardRoute,
  } as any)
const ExploreLibrarySavedIndexRoute =
  ExploreLibrarySavedIndexRouteImport.update({
    id: '/library/saved/',
    path: '/library/saved/',
    getParentRoute: () => ExploreRoute,
  } as any)
const ExploreLibraryRecentIndexRoute =
  ExploreLibraryRecentIndexRouteImport.update({
    id: '/library/recent/',
    path: '/library/recent/',
    getParentRoute: () => ExploreRoute,
  } as any)
const ExploreLibraryPurchasedIndexRoute =
  ExploreLibraryPurchasedIndexRouteImport.update({
    id: '/library/purchased/',
    path: '/library/purchased/',
    getParentRoute: () => ExploreRoute,
  } as any)
const ExploreLibraryPlaylistsIndexRoute =
  ExploreLibraryPlaylistsIndexRouteImport.update({
    id: '/library/playlists/',
    path: '/library/playlists/',
    getParentRoute: () => ExploreRoute,
  } as any)
const DashboardTracksIdEditRoute = DashboardTracksIdEditRouteImport.update({
  id: '/tracks/$id/edit',
  path: '/tracks/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)
const ExploreLibraryPlaylistsIdIndexRoute =
  ExploreLibraryPlaylistsIdIndexRouteImport.update({
    id: '/library/playlists/$id/',
    path: '/library/playlists/$id/',
    getParentRoute: () => ExploreRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ExploreIndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRouteWithChildren
  '/new-releases': typeof ExploreNewReleasesRoute
  '/dashboard/collaborators': typeof DashboardCollaboratorsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/music': typeof DashboardMusicRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/artist/$username': typeof ExploreArtistUsernameRoute
  '/artist/new': typeof ExploreArtistNewRoute
  '/artist/rising-stars': typeof ExploreArtistRisingStarsRoute
  '/artist/top': typeof ExploreArtistTopRoute
  '/battles/$id': typeof ExploreBattlesIdRoute
  '/battles/leaderboard': typeof ExploreBattlesLeaderboardRoute
  '/battles/live': typeof ExploreBattlesLiveRoute
  '/battles/must-see': typeof ExploreBattlesMustSeeRoute
  '/battles/upcoming': typeof ExploreBattlesUpcomingRoute
  '/genres/$id': typeof ExploreGenresIdRoute
  '/library/settings': typeof ExploreLibrarySettingsRoute
  '/tracks/$id': typeof ExploreTracksIdRoute
  '/dashboard/battles/challenge': typeof DashboardBattlesChallengeRoute
  '/dashboard/battles/find': typeof DashboardBattlesFindRoute
  '/dashboard/battles/my-kit': typeof DashboardBattlesMyKitRoute
  '/dashboard/battles/upcoming': typeof DashboardBattlesUpcomingRoute
  '/dashboard/career/ai-studio': typeof DashboardCareerAiStudioRoute
  '/dashboard/career/analytics': typeof DashboardCareerAnalyticsRoute
  '/dashboard/career/profile': typeof DashboardCareerProfileRoute
  '/dashboard/career/settings': typeof DashboardCareerSettingsRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/tracks/new': typeof DashboardTracksNewRoute
  '/signup/artist/credentials': typeof SignupArtistCredentialsRoute
  '/signup/artist/onboarding': typeof SignupArtistOnboardingRoute
  '/signup/fan/credentials': typeof SignupFanCredentialsRoute
  '/signup/fan/onboarding': typeof SignupFanOnboardingRoute
  '/artist/': typeof ExploreArtistIndexRoute
  '/battles/': typeof ExploreBattlesIndexRoute
  '/genres/': typeof ExploreGenresIndexRoute
  '/library/': typeof ExploreLibraryIndexRoute
  '/tracks/': typeof ExploreTracksIndexRoute
  '/dashboard/battles/': typeof DashboardBattlesIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/tracks/': typeof DashboardTracksIndexRoute
  '/dashboard/tracks/$id/edit': typeof DashboardTracksIdEditRoute
  '/library/playlists/': typeof ExploreLibraryPlaylistsIndexRoute
  '/library/purchased/': typeof ExploreLibraryPurchasedIndexRoute
  '/library/recent/': typeof ExploreLibraryRecentIndexRoute
  '/library/saved/': typeof ExploreLibrarySavedIndexRoute
  '/dashboard/battles/my-stats/': typeof DashboardBattlesMyStatsIndexRoute
  '/dashboard/tracks/$id/': typeof DashboardTracksIdIndexRoute
  '/library/playlists/$id/': typeof ExploreLibraryPlaylistsIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRouteWithChildren
  '/new-releases': typeof ExploreNewReleasesRoute
  '/dashboard/collaborators': typeof DashboardCollaboratorsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/music': typeof DashboardMusicRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/': typeof ExploreIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/artist/$username': typeof ExploreArtistUsernameRoute
  '/artist/new': typeof ExploreArtistNewRoute
  '/artist/rising-stars': typeof ExploreArtistRisingStarsRoute
  '/artist/top': typeof ExploreArtistTopRoute
  '/battles/$id': typeof ExploreBattlesIdRoute
  '/battles/leaderboard': typeof ExploreBattlesLeaderboardRoute
  '/battles/live': typeof ExploreBattlesLiveRoute
  '/battles/must-see': typeof ExploreBattlesMustSeeRoute
  '/battles/upcoming': typeof ExploreBattlesUpcomingRoute
  '/genres/$id': typeof ExploreGenresIdRoute
  '/library/settings': typeof ExploreLibrarySettingsRoute
  '/tracks/$id': typeof ExploreTracksIdRoute
  '/dashboard/battles/challenge': typeof DashboardBattlesChallengeRoute
  '/dashboard/battles/find': typeof DashboardBattlesFindRoute
  '/dashboard/battles/my-kit': typeof DashboardBattlesMyKitRoute
  '/dashboard/battles/upcoming': typeof DashboardBattlesUpcomingRoute
  '/dashboard/career/ai-studio': typeof DashboardCareerAiStudioRoute
  '/dashboard/career/analytics': typeof DashboardCareerAnalyticsRoute
  '/dashboard/career/profile': typeof DashboardCareerProfileRoute
  '/dashboard/career/settings': typeof DashboardCareerSettingsRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/tracks/new': typeof DashboardTracksNewRoute
  '/signup/artist/credentials': typeof SignupArtistCredentialsRoute
  '/signup/artist/onboarding': typeof SignupArtistOnboardingRoute
  '/signup/fan/credentials': typeof SignupFanCredentialsRoute
  '/signup/fan/onboarding': typeof SignupFanOnboardingRoute
  '/artist': typeof ExploreArtistIndexRoute
  '/battles': typeof ExploreBattlesIndexRoute
  '/genres': typeof ExploreGenresIndexRoute
  '/library': typeof ExploreLibraryIndexRoute
  '/tracks': typeof ExploreTracksIndexRoute
  '/dashboard/battles': typeof DashboardBattlesIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/tracks': typeof DashboardTracksIndexRoute
  '/dashboard/tracks/$id/edit': typeof DashboardTracksIdEditRoute
  '/library/playlists': typeof ExploreLibraryPlaylistsIndexRoute
  '/library/purchased': typeof ExploreLibraryPurchasedIndexRoute
  '/library/recent': typeof ExploreLibraryRecentIndexRoute
  '/library/saved': typeof ExploreLibrarySavedIndexRoute
  '/dashboard/battles/my-stats': typeof DashboardBattlesMyStatsIndexRoute
  '/dashboard/tracks/$id': typeof DashboardTracksIdIndexRoute
  '/library/playlists/$id': typeof ExploreLibraryPlaylistsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_explore': typeof ExploreRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRouteWithChildren
  '/_explore/new-releases': typeof ExploreNewReleasesRoute
  '/dashboard/collaborators': typeof DashboardCollaboratorsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/music': typeof DashboardMusicRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/_explore/': typeof ExploreIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_explore/artist/$username': typeof ExploreArtistUsernameRoute
  '/_explore/artist/new': typeof ExploreArtistNewRoute
  '/_explore/artist/rising-stars': typeof ExploreArtistRisingStarsRoute
  '/_explore/artist/top': typeof ExploreArtistTopRoute
  '/_explore/battles/$id': typeof ExploreBattlesIdRoute
  '/_explore/battles/leaderboard': typeof ExploreBattlesLeaderboardRoute
  '/_explore/battles/live': typeof ExploreBattlesLiveRoute
  '/_explore/battles/must-see': typeof ExploreBattlesMustSeeRoute
  '/_explore/battles/upcoming': typeof ExploreBattlesUpcomingRoute
  '/_explore/genres/$id': typeof ExploreGenresIdRoute
  '/_explore/library/settings': typeof ExploreLibrarySettingsRoute
  '/_explore/tracks/$id': typeof ExploreTracksIdRoute
  '/dashboard/battles/challenge': typeof DashboardBattlesChallengeRoute
  '/dashboard/battles/find': typeof DashboardBattlesFindRoute
  '/dashboard/battles/my-kit': typeof DashboardBattlesMyKitRoute
  '/dashboard/battles/upcoming': typeof DashboardBattlesUpcomingRoute
  '/dashboard/career/ai-studio': typeof DashboardCareerAiStudioRoute
  '/dashboard/career/analytics': typeof DashboardCareerAnalyticsRoute
  '/dashboard/career/profile': typeof DashboardCareerProfileRoute
  '/dashboard/career/settings': typeof DashboardCareerSettingsRoute
  '/dashboard/projects/$id': typeof DashboardProjectsIdRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/tracks/new': typeof DashboardTracksNewRoute
  '/signup/artist/credentials': typeof SignupArtistCredentialsRoute
  '/signup/artist/onboarding': typeof SignupArtistOnboardingRoute
  '/signup/fan/credentials': typeof SignupFanCredentialsRoute
  '/signup/fan/onboarding': typeof SignupFanOnboardingRoute
  '/_explore/artist/': typeof ExploreArtistIndexRoute
  '/_explore/battles/': typeof ExploreBattlesIndexRoute
  '/_explore/genres/': typeof ExploreGenresIndexRoute
  '/_explore/library/': typeof ExploreLibraryIndexRoute
  '/_explore/tracks/': typeof ExploreTracksIndexRoute
  '/dashboard/battles/': typeof DashboardBattlesIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/tracks/': typeof DashboardTracksIndexRoute
  '/dashboard/tracks/$id/edit': typeof DashboardTracksIdEditRoute
  '/_explore/library/playlists/': typeof ExploreLibraryPlaylistsIndexRoute
  '/_explore/library/purchased/': typeof ExploreLibraryPurchasedIndexRoute
  '/_explore/library/recent/': typeof ExploreLibraryRecentIndexRoute
  '/_explore/library/saved/': typeof ExploreLibrarySavedIndexRoute
  '/dashboard/battles/my-stats/': typeof DashboardBattlesMyStatsIndexRoute
  '/dashboard/tracks/$id/': typeof DashboardTracksIdIndexRoute
  '/_explore/library/playlists/$id/': typeof ExploreLibraryPlaylistsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/new-releases'
    | '/dashboard/collaborators'
    | '/dashboard/messages'
    | '/dashboard/music'
    | '/dashboard/profile'
    | '/dashboard/team'
    | '/dashboard/'
    | '/artist/$username'
    | '/artist/new'
    | '/artist/rising-stars'
    | '/artist/top'
    | '/battles/$id'
    | '/battles/leaderboard'
    | '/battles/live'
    | '/battles/must-see'
    | '/battles/upcoming'
    | '/genres/$id'
    | '/library/settings'
    | '/tracks/$id'
    | '/dashboard/battles/challenge'
    | '/dashboard/battles/find'
    | '/dashboard/battles/my-kit'
    | '/dashboard/battles/upcoming'
    | '/dashboard/career/ai-studio'
    | '/dashboard/career/analytics'
    | '/dashboard/career/profile'
    | '/dashboard/career/settings'
    | '/dashboard/projects/$id'
    | '/dashboard/projects/new'
    | '/dashboard/tracks/new'
    | '/signup/artist/credentials'
    | '/signup/artist/onboarding'
    | '/signup/fan/credentials'
    | '/signup/fan/onboarding'
    | '/artist/'
    | '/battles/'
    | '/genres/'
    | '/library/'
    | '/tracks/'
    | '/dashboard/battles/'
    | '/dashboard/projects/'
    | '/dashboard/tracks/'
    | '/dashboard/tracks/$id/edit'
    | '/library/playlists/'
    | '/library/purchased/'
    | '/library/recent/'
    | '/library/saved/'
    | '/dashboard/battles/my-stats/'
    | '/dashboard/tracks/$id/'
    | '/library/playlists/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/new-releases'
    | '/dashboard/collaborators'
    | '/dashboard/messages'
    | '/dashboard/music'
    | '/dashboard/profile'
    | '/dashboard/team'
    | '/'
    | '/dashboard'
    | '/artist/$username'
    | '/artist/new'
    | '/artist/rising-stars'
    | '/artist/top'
    | '/battles/$id'
    | '/battles/leaderboard'
    | '/battles/live'
    | '/battles/must-see'
    | '/battles/upcoming'
    | '/genres/$id'
    | '/library/settings'
    | '/tracks/$id'
    | '/dashboard/battles/challenge'
    | '/dashboard/battles/find'
    | '/dashboard/battles/my-kit'
    | '/dashboard/battles/upcoming'
    | '/dashboard/career/ai-studio'
    | '/dashboard/career/analytics'
    | '/dashboard/career/profile'
    | '/dashboard/career/settings'
    | '/dashboard/projects/$id'
    | '/dashboard/projects/new'
    | '/dashboard/tracks/new'
    | '/signup/artist/credentials'
    | '/signup/artist/onboarding'
    | '/signup/fan/credentials'
    | '/signup/fan/onboarding'
    | '/artist'
    | '/battles'
    | '/genres'
    | '/library'
    | '/tracks'
    | '/dashboard/battles'
    | '/dashboard/projects'
    | '/dashboard/tracks'
    | '/dashboard/tracks/$id/edit'
    | '/library/playlists'
    | '/library/purchased'
    | '/library/recent'
    | '/library/saved'
    | '/dashboard/battles/my-stats'
    | '/dashboard/tracks/$id'
    | '/library/playlists/$id'
  id:
    | '__root__'
    | '/_explore'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/_explore/new-releases'
    | '/dashboard/collaborators'
    | '/dashboard/messages'
    | '/dashboard/music'
    | '/dashboard/profile'
    | '/dashboard/team'
    | '/_explore/'
    | '/dashboard/'
    | '/_explore/artist/$username'
    | '/_explore/artist/new'
    | '/_explore/artist/rising-stars'
    | '/_explore/artist/top'
    | '/_explore/battles/$id'
    | '/_explore/battles/leaderboard'
    | '/_explore/battles/live'
    | '/_explore/battles/must-see'
    | '/_explore/battles/upcoming'
    | '/_explore/genres/$id'
    | '/_explore/library/settings'
    | '/_explore/tracks/$id'
    | '/dashboard/battles/challenge'
    | '/dashboard/battles/find'
    | '/dashboard/battles/my-kit'
    | '/dashboard/battles/upcoming'
    | '/dashboard/career/ai-studio'
    | '/dashboard/career/analytics'
    | '/dashboard/career/profile'
    | '/dashboard/career/settings'
    | '/dashboard/projects/$id'
    | '/dashboard/projects/new'
    | '/dashboard/tracks/new'
    | '/signup/artist/credentials'
    | '/signup/artist/onboarding'
    | '/signup/fan/credentials'
    | '/signup/fan/onboarding'
    | '/_explore/artist/'
    | '/_explore/battles/'
    | '/_explore/genres/'
    | '/_explore/library/'
    | '/_explore/tracks/'
    | '/dashboard/battles/'
    | '/dashboard/projects/'
    | '/dashboard/tracks/'
    | '/dashboard/tracks/$id/edit'
    | '/_explore/library/playlists/'
    | '/_explore/library/purchased/'
    | '/_explore/library/recent/'
    | '/_explore/library/saved/'
    | '/dashboard/battles/my-stats/'
    | '/dashboard/tracks/$id/'
    | '/_explore/library/playlists/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ExploreRoute: typeof ExploreRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_explore': {
      id: '/_explore'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_explore/': {
      id: '/_explore/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/music': {
      id: '/dashboard/music'
      path: '/music'
      fullPath: '/dashboard/music'
      preLoaderRoute: typeof DashboardMusicRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/collaborators': {
      id: '/dashboard/collaborators'
      path: '/collaborators'
      fullPath: '/dashboard/collaborators'
      preLoaderRoute: typeof DashboardCollaboratorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_explore/new-releases': {
      id: '/_explore/new-releases'
      path: '/new-releases'
      fullPath: '/new-releases'
      preLoaderRoute: typeof ExploreNewReleasesRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/dashboard/tracks/': {
      id: '/dashboard/tracks/'
      path: '/tracks'
      fullPath: '/dashboard/tracks/'
      preLoaderRoute: typeof DashboardTracksIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/battles/': {
      id: '/dashboard/battles/'
      path: '/battles'
      fullPath: '/dashboard/battles/'
      preLoaderRoute: typeof DashboardBattlesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_explore/tracks/': {
      id: '/_explore/tracks/'
      path: '/tracks'
      fullPath: '/tracks/'
      preLoaderRoute: typeof ExploreTracksIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/library/': {
      id: '/_explore/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof ExploreLibraryIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/genres/': {
      id: '/_explore/genres/'
      path: '/genres'
      fullPath: '/genres/'
      preLoaderRoute: typeof ExploreGenresIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/battles/': {
      id: '/_explore/battles/'
      path: '/battles'
      fullPath: '/battles/'
      preLoaderRoute: typeof ExploreBattlesIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/artist/': {
      id: '/_explore/artist/'
      path: '/artist'
      fullPath: '/artist/'
      preLoaderRoute: typeof ExploreArtistIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/signup/fan/onboarding': {
      id: '/signup/fan/onboarding'
      path: '/fan/onboarding'
      fullPath: '/signup/fan/onboarding'
      preLoaderRoute: typeof SignupFanOnboardingRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/fan/credentials': {
      id: '/signup/fan/credentials'
      path: '/fan/credentials'
      fullPath: '/signup/fan/credentials'
      preLoaderRoute: typeof SignupFanCredentialsRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/artist/onboarding': {
      id: '/signup/artist/onboarding'
      path: '/artist/onboarding'
      fullPath: '/signup/artist/onboarding'
      preLoaderRoute: typeof SignupArtistOnboardingRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/artist/credentials': {
      id: '/signup/artist/credentials'
      path: '/artist/credentials'
      fullPath: '/signup/artist/credentials'
      preLoaderRoute: typeof SignupArtistCredentialsRouteImport
      parentRoute: typeof SignupRoute
    }
    '/dashboard/tracks/new': {
      id: '/dashboard/tracks/new'
      path: '/tracks/new'
      fullPath: '/dashboard/tracks/new'
      preLoaderRoute: typeof DashboardTracksNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/new': {
      id: '/dashboard/projects/new'
      path: '/projects/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$id': {
      id: '/dashboard/projects/$id'
      path: '/projects/$id'
      fullPath: '/dashboard/projects/$id'
      preLoaderRoute: typeof DashboardProjectsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/career/settings': {
      id: '/dashboard/career/settings'
      path: '/career/settings'
      fullPath: '/dashboard/career/settings'
      preLoaderRoute: typeof DashboardCareerSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/career/profile': {
      id: '/dashboard/career/profile'
      path: '/career/profile'
      fullPath: '/dashboard/career/profile'
      preLoaderRoute: typeof DashboardCareerProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/career/analytics': {
      id: '/dashboard/career/analytics'
      path: '/career/analytics'
      fullPath: '/dashboard/career/analytics'
      preLoaderRoute: typeof DashboardCareerAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/career/ai-studio': {
      id: '/dashboard/career/ai-studio'
      path: '/career/ai-studio'
      fullPath: '/dashboard/career/ai-studio'
      preLoaderRoute: typeof DashboardCareerAiStudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/battles/upcoming': {
      id: '/dashboard/battles/upcoming'
      path: '/battles/upcoming'
      fullPath: '/dashboard/battles/upcoming'
      preLoaderRoute: typeof DashboardBattlesUpcomingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/battles/my-kit': {
      id: '/dashboard/battles/my-kit'
      path: '/battles/my-kit'
      fullPath: '/dashboard/battles/my-kit'
      preLoaderRoute: typeof DashboardBattlesMyKitRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/battles/find': {
      id: '/dashboard/battles/find'
      path: '/battles/find'
      fullPath: '/dashboard/battles/find'
      preLoaderRoute: typeof DashboardBattlesFindRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/battles/challenge': {
      id: '/dashboard/battles/challenge'
      path: '/battles/challenge'
      fullPath: '/dashboard/battles/challenge'
      preLoaderRoute: typeof DashboardBattlesChallengeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_explore/tracks/$id': {
      id: '/_explore/tracks/$id'
      path: '/tracks/$id'
      fullPath: '/tracks/$id'
      preLoaderRoute: typeof ExploreTracksIdRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/library/settings': {
      id: '/_explore/library/settings'
      path: '/library/settings'
      fullPath: '/library/settings'
      preLoaderRoute: typeof ExploreLibrarySettingsRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/genres/$id': {
      id: '/_explore/genres/$id'
      path: '/genres/$id'
      fullPath: '/genres/$id'
      preLoaderRoute: typeof ExploreGenresIdRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/battles/upcoming': {
      id: '/_explore/battles/upcoming'
      path: '/battles/upcoming'
      fullPath: '/battles/upcoming'
      preLoaderRoute: typeof ExploreBattlesUpcomingRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/battles/must-see': {
      id: '/_explore/battles/must-see'
      path: '/battles/must-see'
      fullPath: '/battles/must-see'
      preLoaderRoute: typeof ExploreBattlesMustSeeRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/battles/live': {
      id: '/_explore/battles/live'
      path: '/battles/live'
      fullPath: '/battles/live'
      preLoaderRoute: typeof ExploreBattlesLiveRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/battles/leaderboard': {
      id: '/_explore/battles/leaderboard'
      path: '/battles/leaderboard'
      fullPath: '/battles/leaderboard'
      preLoaderRoute: typeof ExploreBattlesLeaderboardRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/battles/$id': {
      id: '/_explore/battles/$id'
      path: '/battles/$id'
      fullPath: '/battles/$id'
      preLoaderRoute: typeof ExploreBattlesIdRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/artist/top': {
      id: '/_explore/artist/top'
      path: '/artist/top'
      fullPath: '/artist/top'
      preLoaderRoute: typeof ExploreArtistTopRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/artist/rising-stars': {
      id: '/_explore/artist/rising-stars'
      path: '/artist/rising-stars'
      fullPath: '/artist/rising-stars'
      preLoaderRoute: typeof ExploreArtistRisingStarsRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/artist/new': {
      id: '/_explore/artist/new'
      path: '/artist/new'
      fullPath: '/artist/new'
      preLoaderRoute: typeof ExploreArtistNewRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/artist/$username': {
      id: '/_explore/artist/$username'
      path: '/artist/$username'
      fullPath: '/artist/$username'
      preLoaderRoute: typeof ExploreArtistUsernameRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/dashboard/tracks/$id/': {
      id: '/dashboard/tracks/$id/'
      path: '/tracks/$id'
      fullPath: '/dashboard/tracks/$id/'
      preLoaderRoute: typeof DashboardTracksIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/battles/my-stats/': {
      id: '/dashboard/battles/my-stats/'
      path: '/battles/my-stats'
      fullPath: '/dashboard/battles/my-stats/'
      preLoaderRoute: typeof DashboardBattlesMyStatsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_explore/library/saved/': {
      id: '/_explore/library/saved/'
      path: '/library/saved'
      fullPath: '/library/saved/'
      preLoaderRoute: typeof ExploreLibrarySavedIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/library/recent/': {
      id: '/_explore/library/recent/'
      path: '/library/recent'
      fullPath: '/library/recent/'
      preLoaderRoute: typeof ExploreLibraryRecentIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/library/purchased/': {
      id: '/_explore/library/purchased/'
      path: '/library/purchased'
      fullPath: '/library/purchased/'
      preLoaderRoute: typeof ExploreLibraryPurchasedIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_explore/library/playlists/': {
      id: '/_explore/library/playlists/'
      path: '/library/playlists'
      fullPath: '/library/playlists/'
      preLoaderRoute: typeof ExploreLibraryPlaylistsIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/dashboard/tracks/$id/edit': {
      id: '/dashboard/tracks/$id/edit'
      path: '/tracks/$id/edit'
      fullPath: '/dashboard/tracks/$id/edit'
      preLoaderRoute: typeof DashboardTracksIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_explore/library/playlists/$id/': {
      id: '/_explore/library/playlists/$id/'
      path: '/library/playlists/$id'
      fullPath: '/library/playlists/$id/'
      preLoaderRoute: typeof ExploreLibraryPlaylistsIdIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
  }
}

interface ExploreRouteChildren {
  ExploreNewReleasesRoute: typeof ExploreNewReleasesRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  ExploreArtistUsernameRoute: typeof ExploreArtistUsernameRoute
  ExploreArtistNewRoute: typeof ExploreArtistNewRoute
  ExploreArtistRisingStarsRoute: typeof ExploreArtistRisingStarsRoute
  ExploreArtistTopRoute: typeof ExploreArtistTopRoute
  ExploreBattlesIdRoute: typeof ExploreBattlesIdRoute
  ExploreBattlesLeaderboardRoute: typeof ExploreBattlesLeaderboardRoute
  ExploreBattlesLiveRoute: typeof ExploreBattlesLiveRoute
  ExploreBattlesMustSeeRoute: typeof ExploreBattlesMustSeeRoute
  ExploreBattlesUpcomingRoute: typeof ExploreBattlesUpcomingRoute
  ExploreGenresIdRoute: typeof ExploreGenresIdRoute
  ExploreLibrarySettingsRoute: typeof ExploreLibrarySettingsRoute
  ExploreTracksIdRoute: typeof ExploreTracksIdRoute
  ExploreArtistIndexRoute: typeof ExploreArtistIndexRoute
  ExploreBattlesIndexRoute: typeof ExploreBattlesIndexRoute
  ExploreGenresIndexRoute: typeof ExploreGenresIndexRoute
  ExploreLibraryIndexRoute: typeof ExploreLibraryIndexRoute
  ExploreTracksIndexRoute: typeof ExploreTracksIndexRoute
  ExploreLibraryPlaylistsIndexRoute: typeof ExploreLibraryPlaylistsIndexRoute
  ExploreLibraryPurchasedIndexRoute: typeof ExploreLibraryPurchasedIndexRoute
  ExploreLibraryRecentIndexRoute: typeof ExploreLibraryRecentIndexRoute
  ExploreLibrarySavedIndexRoute: typeof ExploreLibrarySavedIndexRoute
  ExploreLibraryPlaylistsIdIndexRoute: typeof ExploreLibraryPlaylistsIdIndexRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreNewReleasesRoute: ExploreNewReleasesRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  ExploreArtistUsernameRoute: ExploreArtistUsernameRoute,
  ExploreArtistNewRoute: ExploreArtistNewRoute,
  ExploreArtistRisingStarsRoute: ExploreArtistRisingStarsRoute,
  ExploreArtistTopRoute: ExploreArtistTopRoute,
  ExploreBattlesIdRoute: ExploreBattlesIdRoute,
  ExploreBattlesLeaderboardRoute: ExploreBattlesLeaderboardRoute,
  ExploreBattlesLiveRoute: ExploreBattlesLiveRoute,
  ExploreBattlesMustSeeRoute: ExploreBattlesMustSeeRoute,
  ExploreBattlesUpcomingRoute: ExploreBattlesUpcomingRoute,
  ExploreGenresIdRoute: ExploreGenresIdRoute,
  ExploreLibrarySettingsRoute: ExploreLibrarySettingsRoute,
  ExploreTracksIdRoute: ExploreTracksIdRoute,
  ExploreArtistIndexRoute: ExploreArtistIndexRoute,
  ExploreBattlesIndexRoute: ExploreBattlesIndexRoute,
  ExploreGenresIndexRoute: ExploreGenresIndexRoute,
  ExploreLibraryIndexRoute: ExploreLibraryIndexRoute,
  ExploreTracksIndexRoute: ExploreTracksIndexRoute,
  ExploreLibraryPlaylistsIndexRoute: ExploreLibraryPlaylistsIndexRoute,
  ExploreLibraryPurchasedIndexRoute: ExploreLibraryPurchasedIndexRoute,
  ExploreLibraryRecentIndexRoute: ExploreLibraryRecentIndexRoute,
  ExploreLibrarySavedIndexRoute: ExploreLibrarySavedIndexRoute,
  ExploreLibraryPlaylistsIdIndexRoute: ExploreLibraryPlaylistsIdIndexRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface DashboardRouteChildren {
  DashboardCollaboratorsRoute: typeof DashboardCollaboratorsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardMusicRoute: typeof DashboardMusicRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBattlesChallengeRoute: typeof DashboardBattlesChallengeRoute
  DashboardBattlesFindRoute: typeof DashboardBattlesFindRoute
  DashboardBattlesMyKitRoute: typeof DashboardBattlesMyKitRoute
  DashboardBattlesUpcomingRoute: typeof DashboardBattlesUpcomingRoute
  DashboardCareerAiStudioRoute: typeof DashboardCareerAiStudioRoute
  DashboardCareerAnalyticsRoute: typeof DashboardCareerAnalyticsRoute
  DashboardCareerProfileRoute: typeof DashboardCareerProfileRoute
  DashboardCareerSettingsRoute: typeof DashboardCareerSettingsRoute
  DashboardProjectsIdRoute: typeof DashboardProjectsIdRoute
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
  DashboardTracksNewRoute: typeof DashboardTracksNewRoute
  DashboardBattlesIndexRoute: typeof DashboardBattlesIndexRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardTracksIndexRoute: typeof DashboardTracksIndexRoute
  DashboardTracksIdEditRoute: typeof DashboardTracksIdEditRoute
  DashboardBattlesMyStatsIndexRoute: typeof DashboardBattlesMyStatsIndexRoute
  DashboardTracksIdIndexRoute: typeof DashboardTracksIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCollaboratorsRoute: DashboardCollaboratorsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardMusicRoute: DashboardMusicRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBattlesChallengeRoute: DashboardBattlesChallengeRoute,
  DashboardBattlesFindRoute: DashboardBattlesFindRoute,
  DashboardBattlesMyKitRoute: DashboardBattlesMyKitRoute,
  DashboardBattlesUpcomingRoute: DashboardBattlesUpcomingRoute,
  DashboardCareerAiStudioRoute: DashboardCareerAiStudioRoute,
  DashboardCareerAnalyticsRoute: DashboardCareerAnalyticsRoute,
  DashboardCareerProfileRoute: DashboardCareerProfileRoute,
  DashboardCareerSettingsRoute: DashboardCareerSettingsRoute,
  DashboardProjectsIdRoute: DashboardProjectsIdRoute,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
  DashboardTracksNewRoute: DashboardTracksNewRoute,
  DashboardBattlesIndexRoute: DashboardBattlesIndexRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardTracksIndexRoute: DashboardTracksIndexRoute,
  DashboardTracksIdEditRoute: DashboardTracksIdEditRoute,
  DashboardBattlesMyStatsIndexRoute: DashboardBattlesMyStatsIndexRoute,
  DashboardTracksIdIndexRoute: DashboardTracksIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SignupRouteChildren {
  SignupArtistCredentialsRoute: typeof SignupArtistCredentialsRoute
  SignupArtistOnboardingRoute: typeof SignupArtistOnboardingRoute
  SignupFanCredentialsRoute: typeof SignupFanCredentialsRoute
  SignupFanOnboardingRoute: typeof SignupFanOnboardingRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupArtistCredentialsRoute: SignupArtistCredentialsRoute,
  SignupArtistOnboardingRoute: SignupArtistOnboardingRoute,
  SignupFanCredentialsRoute: SignupFanCredentialsRoute,
  SignupFanOnboardingRoute: SignupFanOnboardingRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ExploreRoute: ExploreRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
