/* Generated from world-countries 5.1.0 (ODbL-1.0). Keep this data-only module server-side. */

export type ExploreContinent =
  | "africa"
  | "asia"
  | "europe"
  | "latin-america"
  | "north-america"
  | "oceania";

export interface ExploreCountry {
  aliases: readonly string[];
  name: string;
  scope: ExploreContinent | "global";
  slug: string;
}

export const exploreCountries: readonly ExploreCountry[] = [
  {
    aliases: [
      "af",
      "afg",
      "afghanistan",
      "afġānistān",
      "islamic republic of afghanistan",
    ],
    name: "Afghanistan",
    scope: "asia",
    slug: "afghanistan",
  },
  {
    aliases: ["aaland", "ahvenanmaa", "ala", "aland", "ax", "åland islands"],
    name: "Åland Islands",
    scope: "europe",
    slug: "aland-islands",
  },
  {
    aliases: [
      "al",
      "alb",
      "albania",
      "republic of albania",
      "shqipnia",
      "shqipëri",
      "shqipëria",
    ],
    name: "Albania",
    scope: "europe",
    slug: "albania",
  },
  {
    aliases: [
      "algeria",
      "algérie",
      "dz",
      "dza",
      "dzayer",
      "people's democratic republic of algeria",
    ],
    name: "Algeria",
    scope: "africa",
    slug: "algeria",
  },
  {
    aliases: [
      "amelika sāmoa",
      "american samoa",
      "amerika sāmoa",
      "as",
      "asm",
      "sāmoa amelika",
    ],
    name: "American Samoa",
    scope: "oceania",
    slug: "american-samoa",
  },
  {
    aliases: [
      "ad",
      "and",
      "andorra",
      "principality of andorra",
      "principat d'andorra",
    ],
    name: "Andorra",
    scope: "europe",
    slug: "andorra",
  },
  {
    aliases: [
      "ago",
      "angola",
      "ao",
      "republic of angola",
      "república de angola",
      "ʁɛpublika de an'ɡɔla",
    ],
    name: "Angola",
    scope: "africa",
    slug: "angola",
  },
  {
    aliases: ["ai", "aia", "anguilla"],
    name: "Anguilla",
    scope: "latin-america",
    slug: "anguilla",
  },
  {
    aliases: ["ag", "antigua and barbuda", "atg"],
    name: "Antigua and Barbuda",
    scope: "latin-america",
    slug: "antigua-and-barbuda",
  },
  {
    aliases: [
      "ar",
      "arg",
      "argentina",
      "argentine republic",
      "república argentina",
    ],
    name: "Argentina",
    scope: "latin-america",
    slug: "argentina",
  },
  {
    aliases: [
      "am",
      "arm",
      "armenia",
      "hayastan",
      "republic of armenia",
      "հայաստանի հանրապետություն",
    ],
    name: "Armenia",
    scope: "asia",
    slug: "armenia",
  },
  {
    aliases: ["abw", "aruba", "aw"],
    name: "Aruba",
    scope: "latin-america",
    slug: "aruba",
  },
  {
    aliases: ["au", "aus", "australia", "commonwealth of australia"],
    name: "Australia",
    scope: "oceania",
    slug: "australia",
  },
  {
    aliases: [
      "at",
      "austria",
      "aut",
      "oesterreich",
      "osterreich",
      "republic of austria",
    ],
    name: "Austria",
    scope: "europe",
    slug: "austria",
  },
  {
    aliases: [
      "az",
      "aze",
      "azerbaijan",
      "azərbaycan respublikası",
      "republic of azerbaijan",
    ],
    name: "Azerbaijan",
    scope: "asia",
    slug: "azerbaijan",
  },
  {
    aliases: ["bahamas", "bhs", "bs", "commonwealth of the bahamas"],
    name: "Bahamas",
    scope: "latin-america",
    slug: "bahamas",
  },
  {
    aliases: [
      "bahrain",
      "bh",
      "bhr",
      "kingdom of bahrain",
      "mamlakat al-baḥrayn",
    ],
    name: "Bahrain",
    scope: "asia",
    slug: "bahrain",
  },
  {
    aliases: [
      "bangladesh",
      "bd",
      "bgd",
      "gônôprôjatôntri bangladesh",
      "people's republic of bangladesh",
    ],
    name: "Bangladesh",
    scope: "asia",
    slug: "bangladesh",
  },
  {
    aliases: ["barbados", "bb", "brb"],
    name: "Barbados",
    scope: "latin-america",
    slug: "barbados",
  },
  {
    aliases: [
      "belarus",
      "bielaruś",
      "blr",
      "by",
      "republic of belarus",
      "белоруссия",
      "республика белоруссия",
    ],
    name: "Belarus",
    scope: "europe",
    slug: "belarus",
  },
  {
    aliases: [
      "be",
      "bel",
      "belgie",
      "belgien",
      "belgique",
      "belgium",
      "belgië",
      "kingdom of belgium",
      "koninkrijk belgië",
      "königreich belgien",
      "royaume de belgique",
    ],
    name: "Belgium",
    scope: "europe",
    slug: "belgium",
  },
  {
    aliases: ["belize", "blz", "bz"],
    name: "Belize",
    scope: "latin-america",
    slug: "belize",
  },
  {
    aliases: ["ben", "benin", "bj", "republic of benin", "république du bénin"],
    name: "Benin",
    scope: "africa",
    slug: "benin",
  },
  {
    aliases: [
      "bermuda",
      "bm",
      "bmu",
      "somers isles",
      "the bermudas",
      "the islands of bermuda",
    ],
    name: "Bermuda",
    scope: "north-america",
    slug: "bermuda",
  },
  {
    aliases: ["bhutan", "bt", "btn", "kingdom of bhutan"],
    name: "Bhutan",
    scope: "asia",
    slug: "bhutan",
  },
  {
    aliases: [
      "bo",
      "bol",
      "bolivia",
      "bolivia, plurinational state of",
      "buliwya",
      "buliwya mamallaqta",
      "estado plurinacional de bolivia",
      "plurinational state of bolivia",
      "tetã volívia",
      "wuliwya",
      "wuliwya suyu",
    ],
    name: "Bolivia",
    scope: "latin-america",
    slug: "bolivia",
  },
  {
    aliases: [
      "ba",
      "bih",
      "bosnia and herzegovina",
      "bosnia-herzegovina",
      "босна и херцеговина",
    ],
    name: "Bosnia and Herzegovina",
    scope: "europe",
    slug: "bosnia-and-herzegovina",
  },
  {
    aliases: [
      "botswana",
      "bw",
      "bwa",
      "lefatshe la botswana",
      "republic of botswana",
    ],
    name: "Botswana",
    scope: "africa",
    slug: "botswana",
  },
  {
    aliases: ["bouvet island", "bouvet-øya", "bouvetøya", "bv", "bvt"],
    name: "Bouvet Island",
    scope: "global",
    slug: "bouvet-island",
  },
  {
    aliases: [
      "br",
      "bra",
      "brasil",
      "brazil",
      "federative republic of brazil",
      "república federativa do brasil",
    ],
    name: "Brazil",
    scope: "latin-america",
    slug: "brazil",
  },
  {
    aliases: ["british indian ocean territory", "io", "iot"],
    name: "British Indian Ocean Territory",
    scope: "africa",
    slug: "british-indian-ocean-territory",
  },
  {
    aliases: [
      "british virgin islands",
      "vg",
      "vgb",
      "virgin islands",
      "virgin islands, british",
    ],
    name: "British Virgin Islands",
    scope: "latin-america",
    slug: "british-virgin-islands",
  },
  {
    aliases: [
      "bn",
      "brn",
      "brunei",
      "brunei darussalam",
      "nation of brunei",
      "nation of brunei, abode of peace",
      "the abode of peace",
    ],
    name: "Brunei",
    scope: "asia",
    slug: "brunei",
  },
  {
    aliases: [
      "bg",
      "bgr",
      "bulgaria",
      "republic of bulgaria",
      "република българия",
    ],
    name: "Bulgaria",
    scope: "europe",
    slug: "bulgaria",
  },
  {
    aliases: ["bf", "bfa", "burkina faso"],
    name: "Burkina Faso",
    scope: "africa",
    slug: "burkina-faso",
  },
  {
    aliases: [
      "bdi",
      "bi",
      "burundi",
      "republic of burundi",
      "republika y'uburundi",
      "république du burundi",
    ],
    name: "Burundi",
    scope: "africa",
    slug: "burundi",
  },
  {
    aliases: ["cambodia", "kh", "khm", "kingdom of cambodia"],
    name: "Cambodia",
    scope: "asia",
    slug: "cambodia",
  },
  {
    aliases: [
      "cameroon",
      "cm",
      "cmr",
      "republic of cameroon",
      "république du cameroun",
    ],
    name: "Cameroon",
    scope: "africa",
    slug: "cameroon",
  },
  {
    aliases: ["ca", "can", "canada"],
    name: "Canada",
    scope: "north-america",
    slug: "canada",
  },
  {
    aliases: [
      "cape verde",
      "cpv",
      "cv",
      "republic of cabo verde",
      "república de cabo verde",
    ],
    name: "Cape Verde",
    scope: "africa",
    slug: "cape-verde",
  },
  {
    aliases: [
      "bes",
      "bes islands",
      "bonaire sint eustatius and saba",
      "bonaire, sint eustatius and saba",
      "bq",
      "caribbean netherlands",
    ],
    name: "Caribbean Netherlands",
    scope: "latin-america",
    slug: "caribbean-netherlands",
  },
  {
    aliases: ["cayman islands", "cym", "ky"],
    name: "Cayman Islands",
    scope: "latin-america",
    slug: "cayman-islands",
  },
  {
    aliases: [
      "caf",
      "central african republic",
      "cf",
      "république centrafricaine",
    ],
    name: "Central African Republic",
    scope: "africa",
    slug: "central-african-republic",
  },
  {
    aliases: [
      "chad",
      "republic of chad",
      "république du tchad",
      "tcd",
      "tchad",
      "td",
    ],
    name: "Chad",
    scope: "africa",
    slug: "chad",
  },
  {
    aliases: ["chile", "chl", "cl", "republic of chile", "república de chile"],
    name: "Chile",
    scope: "latin-america",
    slug: "chile",
  },
  {
    aliases: [
      "china",
      "chn",
      "cn",
      "people's republic of china",
      "zhongguo",
      "zhonghua",
      "zhōngguó",
      "zhōnghuá rénmín gònghéguó",
      "中华人民共和国",
    ],
    name: "China",
    scope: "asia",
    slug: "china",
  },
  {
    aliases: ["christmas island", "cx", "cxr", "territory of christmas island"],
    name: "Christmas Island",
    scope: "oceania",
    slug: "christmas-island",
  },
  {
    aliases: [
      "cc",
      "cck",
      "cocos (keeling) islands",
      "cocos islands",
      "keeling islands",
      "territory of the cocos (keeling) islands",
    ],
    name: "Cocos (Keeling) Islands",
    scope: "oceania",
    slug: "cocos-keeling-islands",
  },
  {
    aliases: [
      "co",
      "col",
      "colombia",
      "republic of colombia",
      "república de colombia",
    ],
    name: "Colombia",
    scope: "latin-america",
    slug: "colombia",
  },
  {
    aliases: [
      "al-ittiḥād al-qumurī",
      "com",
      "comoros",
      "km",
      "udzima wa komori",
      "union des comores",
      "union of the comoros",
    ],
    name: "Comoros",
    scope: "africa",
    slug: "comoros",
  },
  {
    aliases: ["ck", "cok", "cook islands", "kūki 'āirani"],
    name: "Cook Islands",
    scope: "oceania",
    slug: "cook-islands",
  },
  {
    aliases: [
      "costa rica",
      "cr",
      "cri",
      "republic of costa rica",
      "república de costa rica",
    ],
    name: "Costa Rica",
    scope: "latin-america",
    slug: "costa-rica",
  },
  {
    aliases: [
      "croatia",
      "hr",
      "hrv",
      "hrvatska",
      "republic of croatia",
      "republika hrvatska",
    ],
    name: "Croatia",
    scope: "europe",
    slug: "croatia",
  },
  {
    aliases: ["cu", "cub", "cuba", "republic of cuba", "república de cuba"],
    name: "Cuba",
    scope: "latin-america",
    slug: "cuba",
  },
  {
    aliases: [
      "country of curaçao",
      "curacao",
      "curaçao",
      "cuw",
      "cw",
      "kòrsou",
      "land curaçao",
      "pais kòrsou",
    ],
    name: "Curaçao",
    scope: "latin-america",
    slug: "curacao",
  },
  {
    aliases: [
      "cy",
      "cyp",
      "cyprus",
      "kýpros",
      "kıbrıs",
      "kıbrıs cumhuriyeti",
      "republic of cyprus",
      "κυπριακή δημοκρατία",
    ],
    name: "Cyprus",
    scope: "europe",
    slug: "cyprus",
  },
  {
    aliases: [
      "cz",
      "cze",
      "czech republic",
      "czechia",
      "česko",
      "česká republika",
    ],
    name: "Czechia",
    scope: "europe",
    slug: "czechia",
  },
  {
    aliases: [
      "danmark",
      "denmark",
      "dk",
      "dnk",
      "kingdom of denmark",
      "kongeriget danmark",
    ],
    name: "Denmark",
    scope: "europe",
    slug: "denmark",
  },
  {
    aliases: [
      "dj",
      "dji",
      "djibouti",
      "gabuuti",
      "gabuutih ummuuno",
      "jabuuti",
      "jamhuuriyadda jabuuti",
      "republic of djibouti",
      "république de djibouti",
    ],
    name: "Djibouti",
    scope: "africa",
    slug: "djibouti",
  },
  {
    aliases: [
      "commonwealth of dominica",
      "dm",
      "dma",
      "dominica",
      "dominique",
      "wai‘tu kubuli",
    ],
    name: "Dominica",
    scope: "latin-america",
    slug: "dominica",
  },
  {
    aliases: ["do", "dom", "dominican republic"],
    name: "Dominican Republic",
    scope: "latin-america",
    slug: "dominican-republic",
  },
  {
    aliases: [
      "cd",
      "cod",
      "congo, the democratic republic of the",
      "congo-kinshasa",
      "democratic republic of congo",
      "democratic republic of the congo",
      "dr congo",
      "drc",
    ],
    name: "DR Congo",
    scope: "africa",
    slug: "dr-congo",
  },
  {
    aliases: [
      "ec",
      "ecu",
      "ecuador",
      "republic of ecuador",
      "república del ecuador",
    ],
    name: "Ecuador",
    scope: "latin-america",
    slug: "ecuador",
  },
  {
    aliases: ["arab republic of egypt", "eg", "egy", "egypt"],
    name: "Egypt",
    scope: "africa",
    slug: "egypt",
  },
  {
    aliases: [
      "el salvador",
      "republic of el salvador",
      "república de el salvador",
      "slv",
      "sv",
    ],
    name: "El Salvador",
    scope: "latin-america",
    slug: "el-salvador",
  },
  {
    aliases: [
      "equatorial guinea",
      "gnq",
      "gq",
      "republic of equatorial guinea",
      "república da guiné equatorial",
      "república de guinea ecuatorial",
      "république de guinée équatoriale",
    ],
    name: "Equatorial Guinea",
    scope: "africa",
    slug: "equatorial-guinea",
  },
  {
    aliases: [
      "dawlat iritriyá",
      "er",
      "eri",
      "eritrea",
      "iritriyā",
      "state of eritrea",
      "ʾertrā",
      "ሃገረ ኤርትራ",
    ],
    name: "Eritrea",
    scope: "africa",
    slug: "eritrea",
  },
  {
    aliases: [
      "ee",
      "eesti",
      "eesti vabariik",
      "est",
      "estonia",
      "republic of estonia",
    ],
    name: "Estonia",
    scope: "europe",
    slug: "estonia",
  },
  {
    aliases: [
      "eswatini",
      "kingdom of eswatini",
      "ngwane",
      "swatini",
      "swaziland",
      "swz",
      "sz",
      "umbuso weswatini",
      "weswatini",
    ],
    name: "Eswatini",
    scope: "africa",
    slug: "eswatini",
  },
  {
    aliases: [
      "et",
      "eth",
      "ethiopia",
      "federal democratic republic of ethiopia",
      "ʾītyōṗṗyā",
      "የኢትዮጵያ ፌዴራላዊ ዲሞክራሲያዊ ሪፐብሊክ",
    ],
    name: "Ethiopia",
    scope: "africa",
    slug: "ethiopia",
  },
  {
    aliases: [
      "falkland islands",
      "falkland islands (malvinas)",
      "fk",
      "flk",
      "islas malvinas",
    ],
    name: "Falkland Islands",
    scope: "latin-america",
    slug: "falkland-islands",
  },
  {
    aliases: [
      "faeroe islands",
      "faroe islands",
      "fo",
      "fro",
      "færøerne",
      "føroyar",
    ],
    name: "Faroe Islands",
    scope: "europe",
    slug: "faroe-islands",
  },
  {
    aliases: [
      "fiji",
      "fijī gaṇarājya",
      "fj",
      "fji",
      "matanitu ko viti",
      "republic of fiji",
      "viti",
    ],
    name: "Fiji",
    scope: "oceania",
    slug: "fiji",
  },
  {
    aliases: [
      "fi",
      "fin",
      "finland",
      "republic of finland",
      "republiken finland",
      "suomen tasavalta",
      "suomi",
    ],
    name: "Finland",
    scope: "europe",
    slug: "finland",
  },
  {
    aliases: ["fr", "fra", "france", "french republic", "république française"],
    name: "France",
    scope: "europe",
    slug: "france",
  },
  {
    aliases: ["french guiana", "gf", "guf", "guiana", "guyane"],
    name: "French Guiana",
    scope: "latin-america",
    slug: "french-guiana",
  },
  {
    aliases: [
      "french polynesia",
      "pf",
      "polynésie française",
      "pyf",
      "pōrīnetia farāni",
    ],
    name: "French Polynesia",
    scope: "oceania",
    slug: "french-polynesia",
  },
  {
    aliases: [
      "atf",
      "french southern and antarctic lands",
      "french southern territories",
      "territory of the french southern and antarctic lands",
      "tf",
    ],
    name: "French Southern and Antarctic Lands",
    scope: "global",
    slug: "french-southern-and-antarctic-lands",
  },
  {
    aliases: [
      "ga",
      "gab",
      "gabon",
      "gabonese republic",
      "république gabonaise",
    ],
    name: "Gabon",
    scope: "africa",
    slug: "gabon",
  },
  {
    aliases: ["gambia", "gm", "gmb", "republic of the gambia"],
    name: "Gambia",
    scope: "africa",
    slug: "gambia",
  },
  {
    aliases: ["ge", "geo", "georgia", "sakartvelo"],
    name: "Georgia",
    scope: "asia",
    slug: "georgia",
  },
  {
    aliases: [
      "bundesrepublik deutschland",
      "de",
      "deu",
      "federal republic of germany",
      "germany",
    ],
    name: "Germany",
    scope: "europe",
    slug: "germany",
  },
  {
    aliases: ["gh", "gha", "ghana", "republic of ghana"],
    name: "Ghana",
    scope: "africa",
    slug: "ghana",
  },
  {
    aliases: ["gi", "gib", "gibraltar"],
    name: "Gibraltar",
    scope: "europe",
    slug: "gibraltar",
  },
  {
    aliases: [
      "elláda",
      "gr",
      "grc",
      "greece",
      "hellenic republic",
      "ελληνική δημοκρατία",
    ],
    name: "Greece",
    scope: "europe",
    slug: "greece",
  },
  {
    aliases: ["gl", "greenland", "grl", "grønland"],
    name: "Greenland",
    scope: "north-america",
    slug: "greenland",
  },
  {
    aliases: ["gd", "grd", "grenada"],
    name: "Grenada",
    scope: "latin-america",
    slug: "grenada",
  },
  {
    aliases: ["glp", "gp", "guadeloupe", "gwadloup"],
    name: "Guadeloupe",
    scope: "latin-america",
    slug: "guadeloupe",
  },
  {
    aliases: ["gu", "guam", "gum", "guåhån"],
    name: "Guam",
    scope: "oceania",
    slug: "guam",
  },
  {
    aliases: ["gt", "gtm", "guatemala", "republic of guatemala"],
    name: "Guatemala",
    scope: "latin-america",
    slug: "guatemala",
  },
  {
    aliases: [
      "bailiwick of guernsey",
      "bailliage de guernesey",
      "gg",
      "ggy",
      "guernsey",
    ],
    name: "Guernsey",
    scope: "europe",
    slug: "guernsey",
  },
  {
    aliases: [
      "gin",
      "gn",
      "guinea",
      "republic of guinea",
      "république de guinée",
    ],
    name: "Guinea",
    scope: "africa",
    slug: "guinea",
  },
  {
    aliases: [
      "gnb",
      "guinea-bissau",
      "gw",
      "republic of guinea-bissau",
      "república da guiné-bissau",
    ],
    name: "Guinea-Bissau",
    scope: "africa",
    slug: "guinea-bissau",
  },
  {
    aliases: ["co-operative republic of guyana", "guy", "guyana", "gy"],
    name: "Guyana",
    scope: "latin-america",
    slug: "guyana",
  },
  {
    aliases: [
      "haiti",
      "ht",
      "hti",
      "repiblik ayiti",
      "republic of haiti",
      "république d'haïti",
    ],
    name: "Haiti",
    scope: "latin-america",
    slug: "haiti",
  },
  {
    aliases: ["heard island and mcdonald islands", "hm", "hmd"],
    name: "Heard Island and McDonald Islands",
    scope: "global",
    slug: "heard-island-and-mcdonald-islands",
  },
  {
    aliases: [
      "hn",
      "hnd",
      "honduras",
      "republic of honduras",
      "república de honduras",
    ],
    name: "Honduras",
    scope: "latin-america",
    slug: "honduras",
  },
  {
    aliases: [
      "hk",
      "hkg",
      "hong kong",
      "hong kong special administrative region of the people's republic of china",
    ],
    name: "Hong Kong",
    scope: "asia",
    slug: "hong-kong",
  },
  {
    aliases: ["hu", "hun", "hungary"],
    name: "Hungary",
    scope: "europe",
    slug: "hungary",
  },
  {
    aliases: [
      "iceland",
      "is",
      "isl",
      "island",
      "lýðveldið ísland",
      "republic of iceland",
    ],
    name: "Iceland",
    scope: "europe",
    slug: "iceland",
  },
  {
    aliases: [
      "bharat ganrajya",
      "bhārat",
      "in",
      "ind",
      "india",
      "republic of india",
      "இந்தியா",
    ],
    name: "India",
    scope: "asia",
    slug: "india",
  },
  {
    aliases: [
      "id",
      "idn",
      "indonesia",
      "republic of indonesia",
      "republik indonesia",
    ],
    name: "Indonesia",
    scope: "asia",
    slug: "indonesia",
  },
  {
    aliases: [
      "ir",
      "iran",
      "iran, islamic republic of",
      "irn",
      "islamic republic of iran",
      "jomhuri-ye eslāmi-ye irān",
    ],
    name: "Iran",
    scope: "asia",
    slug: "iran",
  },
  {
    aliases: ["iq", "iraq", "irq", "jumhūriyyat al-‘irāq", "republic of iraq"],
    name: "Iraq",
    scope: "asia",
    slug: "iraq",
  },
  {
    aliases: [
      "ie",
      "ireland",
      "irl",
      "poblacht na héireann",
      "republic of ireland",
      "éire",
    ],
    name: "Ireland",
    scope: "europe",
    slug: "ireland",
  },
  {
    aliases: ["ellan vannin", "im", "imn", "isle of man", "mann", "mannin"],
    name: "Isle of Man",
    scope: "europe",
    slug: "isle-of-man",
  },
  {
    aliases: ["il", "isr", "israel", "medīnat yisrā'el", "state of israel"],
    name: "Israel",
    scope: "asia",
    slug: "israel",
  },
  {
    aliases: ["it", "ita", "italian republic", "italy", "repubblica italiana"],
    name: "Italy",
    scope: "europe",
    slug: "italy",
  },
  {
    aliases: [
      "ci",
      "civ",
      "cote d'ivoire",
      "côte d'ivoire",
      "ivory coast",
      "republic of côte d'ivoire",
      "république de côte d'ivoire",
    ],
    name: "Ivory Coast",
    scope: "africa",
    slug: "ivory-coast",
  },
  {
    aliases: ["jam", "jamaica", "jm"],
    name: "Jamaica",
    scope: "latin-america",
    slug: "jamaica",
  },
  {
    aliases: ["japan", "jp", "jpn", "nihon", "nippon"],
    name: "Japan",
    scope: "asia",
    slug: "japan",
  },
  {
    aliases: [
      "bailiwick of jersey",
      "bailliage de jersey",
      "bailliage dé jèrri",
      "je",
      "jersey",
      "jey",
    ],
    name: "Jersey",
    scope: "europe",
    slug: "jersey",
  },
  {
    aliases: [
      "al-mamlakah al-urdunīyah al-hāshimīyah",
      "hashemite kingdom of jordan",
      "jo",
      "jor",
      "jordan",
    ],
    name: "Jordan",
    scope: "asia",
    slug: "jordan",
  },
  {
    aliases: [
      "kaz",
      "kazakhstan",
      "kz",
      "qazaqstan",
      "qazaqstan respublïkası",
      "republic of kazakhstan",
      "respublika kazakhstan",
      "казахстан",
      "республика казахстан",
      "қазақстан республикасы",
    ],
    name: "Kazakhstan",
    scope: "asia",
    slug: "kazakhstan",
  },
  {
    aliases: ["jamhuri ya kenya", "ke", "ken", "kenya", "republic of kenya"],
    name: "Kenya",
    scope: "africa",
    slug: "kenya",
  },
  {
    aliases: [
      "independent and sovereign republic of kiribati",
      "ki",
      "kir",
      "kiribati",
      "republic of kiribati",
      "ribaberiki kiribati",
    ],
    name: "Kiribati",
    scope: "oceania",
    slug: "kiribati",
  },
  {
    aliases: ["kosovo", "republic of kosovo", "unk", "xk", "република косово"],
    name: "Kosovo",
    scope: "europe",
    slug: "kosovo",
  },
  {
    aliases: ["dawlat al-kuwait", "kuwait", "kw", "kwt", "state of kuwait"],
    name: "Kuwait",
    scope: "asia",
    slug: "kuwait",
  },
  {
    aliases: [
      "kg",
      "kgz",
      "kyrgyz republic",
      "kyrgyz respublikasy",
      "kyrgyzstan",
      "киргизия",
      "кыргыз республикасы",
    ],
    name: "Kyrgyzstan",
    scope: "asia",
    slug: "kyrgyzstan",
  },
  {
    aliases: [
      "la",
      "lao",
      "lao people's democratic republic",
      "laos",
      "sathalanalat paxathipatai paxaxon lao",
    ],
    name: "Laos",
    scope: "asia",
    slug: "laos",
  },
  {
    aliases: [
      "latvia",
      "latvijas republika",
      "lv",
      "lva",
      "republic of latvia",
    ],
    name: "Latvia",
    scope: "europe",
    slug: "latvia",
  },
  {
    aliases: [
      "al-jumhūrīyah al-libnānīyah",
      "lb",
      "lbn",
      "lebanese republic",
      "lebanon",
    ],
    name: "Lebanon",
    scope: "asia",
    slug: "lebanon",
  },
  {
    aliases: ["kingdom of lesotho", "lesotho", "ls", "lso", "muso oa lesotho"],
    name: "Lesotho",
    scope: "africa",
    slug: "lesotho",
  },
  {
    aliases: ["lbr", "liberia", "lr", "republic of liberia"],
    name: "Liberia",
    scope: "africa",
    slug: "liberia",
  },
  {
    aliases: ["dawlat libya", "lby", "libya", "ly", "state of libya"],
    name: "Libya",
    scope: "africa",
    slug: "libya",
  },
  {
    aliases: [
      "fürstentum liechtenstein",
      "li",
      "lie",
      "liechtenstein",
      "principality of liechtenstein",
    ],
    name: "Liechtenstein",
    scope: "europe",
    slug: "liechtenstein",
  },
  {
    aliases: [
      "lietuvos respublika",
      "lithuania",
      "lt",
      "ltu",
      "republic of lithuania",
    ],
    name: "Lithuania",
    scope: "europe",
    slug: "lithuania",
  },
  {
    aliases: [
      "grand duchy of luxembourg",
      "grand-duché de luxembourg",
      "groussherzogtum lëtzebuerg",
      "großherzogtum luxemburg",
      "lu",
      "lux",
      "luxembourg",
    ],
    name: "Luxembourg",
    scope: "europe",
    slug: "luxembourg",
  },
  {
    aliases: [
      "mac",
      "macao",
      "macao special administrative region of the people's republic of china",
      "macau",
      "mo",
      "região administrativa especial de macau da república popular da china",
      "中華人民共和國澳門特別行政區",
      "澳门",
    ],
    name: "Macau",
    scope: "asia",
    slug: "macau",
  },
  {
    aliases: [
      "madagascar",
      "mdg",
      "mg",
      "repoblikan'i madagasikara",
      "republic of madagascar",
      "république de madagascar",
    ],
    name: "Madagascar",
    scope: "africa",
    slug: "madagascar",
  },
  {
    aliases: ["malawi", "mw", "mwi", "republic of malawi"],
    name: "Malawi",
    scope: "africa",
    slug: "malawi",
  },
  {
    aliases: ["malaysia", "my", "mys"],
    name: "Malaysia",
    scope: "asia",
    slug: "malaysia",
  },
  {
    aliases: [
      "dhivehi raajjeyge jumhooriyya",
      "maldive islands",
      "maldives",
      "mdv",
      "mv",
      "republic of the maldives",
    ],
    name: "Maldives",
    scope: "asia",
    slug: "maldives",
  },
  {
    aliases: ["mali", "ml", "mli", "republic of mali", "république du mali"],
    name: "Mali",
    scope: "africa",
    slug: "mali",
  },
  {
    aliases: [
      "malta",
      "mlt",
      "mt",
      "repubblika ta' malta",
      "republic of malta",
    ],
    name: "Malta",
    scope: "europe",
    slug: "malta",
  },
  {
    aliases: [
      "aolepān aorōkin m̧ajeļ",
      "marshall islands",
      "mh",
      "mhl",
      "republic of the marshall islands",
    ],
    name: "Marshall Islands",
    scope: "oceania",
    slug: "marshall-islands",
  },
  {
    aliases: ["martinique", "mq", "mtq"],
    name: "Martinique",
    scope: "latin-america",
    slug: "martinique",
  },
  {
    aliases: [
      "al-jumhūriyyah al-ʾislāmiyyah al-mūrītāniyyah",
      "islamic republic of mauritania",
      "mauritania",
      "mr",
      "mrt",
    ],
    name: "Mauritania",
    scope: "africa",
    slug: "mauritania",
  },
  {
    aliases: [
      "mauritius",
      "mu",
      "mus",
      "republic of mauritius",
      "république de maurice",
    ],
    name: "Mauritius",
    scope: "africa",
    slug: "mauritius",
  },
  {
    aliases: [
      "department of mayotte",
      "département de mayotte",
      "mayotte",
      "myt",
      "yt",
    ],
    name: "Mayotte",
    scope: "africa",
    slug: "mayotte",
  },
  {
    aliases: [
      "estados unidos mexicanos",
      "mex",
      "mexicanos",
      "mexico",
      "mx",
      "united mexican states",
    ],
    name: "Mexico",
    scope: "north-america",
    slug: "mexico",
  },
  {
    aliases: [
      "federated states of micronesia",
      "fm",
      "fsm",
      "micronesia",
      "micronesia, federated states of",
    ],
    name: "Micronesia",
    scope: "oceania",
    slug: "micronesia",
  },
  {
    aliases: [
      "md",
      "mda",
      "moldova",
      "moldova, republic of",
      "republic of moldova",
      "republica moldova",
    ],
    name: "Moldova",
    scope: "europe",
    slug: "moldova",
  },
  {
    aliases: [
      "mc",
      "mco",
      "monaco",
      "principality of monaco",
      "principauté de monaco",
    ],
    name: "Monaco",
    scope: "europe",
    slug: "monaco",
  },
  {
    aliases: ["mn", "mng", "mongolia"],
    name: "Mongolia",
    scope: "asia",
    slug: "mongolia",
  },
  {
    aliases: ["crna gora", "me", "mne", "montenegro"],
    name: "Montenegro",
    scope: "europe",
    slug: "montenegro",
  },
  {
    aliases: ["montserrat", "ms", "msr"],
    name: "Montserrat",
    scope: "latin-america",
    slug: "montserrat",
  },
  {
    aliases: [
      "al-mamlakah al-maġribiyah",
      "kingdom of morocco",
      "ma",
      "mar",
      "morocco",
    ],
    name: "Morocco",
    scope: "africa",
    slug: "morocco",
  },
  {
    aliases: [
      "moz",
      "mozambique",
      "mz",
      "republic of mozambique",
      "república de moçambique",
    ],
    name: "Mozambique",
    scope: "africa",
    slug: "mozambique",
  },
  {
    aliases: [
      "burma",
      "mm",
      "mmr",
      "myanmar",
      "pyidaunzu thanmăda myăma nainngandaw",
      "republic of the union of myanmar",
    ],
    name: "Myanmar",
    scope: "asia",
    slug: "myanmar",
  },
  {
    aliases: ["na", "nam", "namibia", "namibië", "republic of namibia"],
    name: "Namibia",
    scope: "africa",
    slug: "namibia",
  },
  {
    aliases: [
      "naoero",
      "nauru",
      "nr",
      "nru",
      "pleasant island",
      "republic of nauru",
      "ripublik naoero",
    ],
    name: "Nauru",
    scope: "oceania",
    slug: "nauru",
  },
  {
    aliases: [
      "federal democratic republic of nepal",
      "loktāntrik ganatantra nepāl",
      "nepal",
      "np",
      "npl",
    ],
    name: "Nepal",
    scope: "asia",
    slug: "nepal",
  },
  {
    aliases: [
      "holland",
      "kingdom of the netherlands",
      "nederland",
      "netherlands",
      "nl",
      "nld",
      "the netherlands",
    ],
    name: "Netherlands",
    scope: "europe",
    slug: "netherlands",
  },
  {
    aliases: ["nc", "ncl", "new caledonia"],
    name: "New Caledonia",
    scope: "oceania",
    slug: "new-caledonia",
  },
  {
    aliases: ["aotearoa", "new zealand", "nz", "nzl"],
    name: "New Zealand",
    scope: "oceania",
    slug: "new-zealand",
  },
  {
    aliases: [
      "ni",
      "nic",
      "nicaragua",
      "republic of nicaragua",
      "república de nicaragua",
    ],
    name: "Nicaragua",
    scope: "latin-america",
    slug: "nicaragua",
  },
  {
    aliases: ["ne", "ner", "niger", "nijar", "republic of niger"],
    name: "Niger",
    scope: "africa",
    slug: "niger",
  },
  {
    aliases: [
      "federal republic of nigeria",
      "naíjíríà",
      "ng",
      "nga",
      "nigeria",
      "nijeriya",
    ],
    name: "Nigeria",
    scope: "africa",
    slug: "nigeria",
  },
  {
    aliases: ["niu", "niue", "nu"],
    name: "Niue",
    scope: "oceania",
    slug: "niue",
  },
  {
    aliases: [
      "nf",
      "nfk",
      "norfolk island",
      "teratri of norf'k ailen",
      "territory of norfolk island",
    ],
    name: "Norfolk Island",
    scope: "oceania",
    slug: "norfolk-island",
  },
  {
    aliases: [
      "chosŏn minjujuŭi inmin konghwaguk",
      "democratic people's republic of korea",
      "dprk",
      "korea, democratic people's republic of",
      "kp",
      "north korea",
      "prk",
      "북조선",
      "북한",
      "조선민주주의인민공화국",
    ],
    name: "North Korea",
    scope: "asia",
    slug: "north-korea",
  },
  {
    aliases: [
      "macedonia",
      "macedonia, the former yugoslav republic of",
      "mk",
      "mkd",
      "north macedonia",
      "republic of north macedonia",
      "the former yugoslav republic of macedonia",
      "република северна македонија",
    ],
    name: "North Macedonia",
    scope: "europe",
    slug: "north-macedonia",
  },
  {
    aliases: [
      "commonwealth of the northern mariana islands",
      "mnp",
      "mp",
      "northern mariana islands",
      "sankattan siha na islas mariånas",
    ],
    name: "Northern Mariana Islands",
    scope: "oceania",
    slug: "northern-mariana-islands",
  },
  {
    aliases: [
      "kingdom of norway",
      "kongeriket noreg",
      "kongeriket norge",
      "no",
      "nor",
      "noreg",
      "norge",
      "norway",
    ],
    name: "Norway",
    scope: "europe",
    slug: "norway",
  },
  {
    aliases: ["om", "oman", "omn", "salṭanat ʻumān", "sultanate of oman"],
    name: "Oman",
    scope: "asia",
    slug: "oman",
  },
  {
    aliases: [
      "islamic republic of pakistan",
      "islāmī jumhūriya'eh pākistān",
      "pak",
      "pakistan",
      "pk",
      "pākistān",
    ],
    name: "Pakistan",
    scope: "asia",
    slug: "pakistan",
  },
  {
    aliases: ["beluu er a belau", "palau", "plw", "pw", "republic of palau"],
    name: "Palau",
    scope: "oceania",
    slug: "palau",
  },
  {
    aliases: [
      "dawlat filasṭin",
      "palestine",
      "palestine, state of",
      "ps",
      "pse",
      "state of palestine",
    ],
    name: "Palestine",
    scope: "asia",
    slug: "palestine",
  },
  {
    aliases: [
      "pa",
      "pan",
      "panama",
      "republic of panama",
      "república de panamá",
    ],
    name: "Panama",
    scope: "latin-america",
    slug: "panama",
  },
  {
    aliases: [
      "independen stet bilong papua niugini",
      "independent state of papua new guinea",
      "papua new guinea",
      "pg",
      "png",
    ],
    name: "Papua New Guinea",
    scope: "oceania",
    slug: "papua-new-guinea",
  },
  {
    aliases: [
      "paraguay",
      "pry",
      "py",
      "republic of paraguay",
      "república del paraguay",
      "tetã paraguái",
    ],
    name: "Paraguay",
    scope: "latin-america",
    slug: "paraguay",
  },
  {
    aliases: ["pe", "per", "peru", "republic of peru", "república del perú"],
    name: "Peru",
    scope: "latin-america",
    slug: "peru",
  },
  {
    aliases: [
      "ph",
      "philippines",
      "phl",
      "republic of the philippines",
      "repúblika ng pilipinas",
    ],
    name: "Philippines",
    scope: "asia",
    slug: "philippines",
  },
  {
    aliases: [
      "pcn",
      "pitcairn",
      "pitcairn group of islands",
      "pitcairn henderson ducie and oeno islands",
      "pitcairn islands",
      "pn",
    ],
    name: "Pitcairn Islands",
    scope: "oceania",
    slug: "pitcairn-islands",
  },
  {
    aliases: [
      "pl",
      "pol",
      "poland",
      "republic of poland",
      "rzeczpospolita polska",
    ],
    name: "Poland",
    scope: "europe",
    slug: "poland",
  },
  {
    aliases: [
      "portugal",
      "portuguesa",
      "portuguese republic",
      "prt",
      "pt",
      "república portuguesa",
    ],
    name: "Portugal",
    scope: "europe",
    slug: "portugal",
  },
  {
    aliases: [
      "commonwealth of puerto rico",
      "estado libre asociado de puerto rico",
      "pr",
      "pri",
      "puerto rico",
    ],
    name: "Puerto Rico",
    scope: "latin-america",
    slug: "puerto-rico",
  },
  {
    aliases: ["dawlat qaṭar", "qa", "qat", "qatar", "state of qatar"],
    name: "Qatar",
    scope: "asia",
    slug: "qatar",
  },
  {
    aliases: [
      "cg",
      "cog",
      "congo",
      "congo-brazzaville",
      "republic of the congo",
    ],
    name: "Republic of the Congo",
    scope: "africa",
    slug: "republic-of-the-congo",
  },
  {
    aliases: ["re", "reu", "reunion", "réunion", "réunion island"],
    name: "Réunion",
    scope: "africa",
    slug: "reunion",
  },
  {
    aliases: ["ro", "romania", "românia", "rou", "roumania", "rumania"],
    name: "Romania",
    scope: "europe",
    slug: "romania",
  },
  {
    aliases: [
      "ru",
      "rus",
      "russia",
      "russian federation",
      "российская федерация",
    ],
    name: "Russia",
    scope: "europe",
    slug: "russia",
  },
  {
    aliases: [
      "republic of rwanda",
      "repubulika y'u rwanda",
      "rw",
      "rwa",
      "rwanda",
      "république du rwanda",
    ],
    name: "Rwanda",
    scope: "africa",
    slug: "rwanda",
  },
  {
    aliases: [
      "bl",
      "blm",
      "collectivity of saint barthélemy",
      "collectivité de saint-barthélemy",
      "saint barthélemy",
      "st. barthelemy",
    ],
    name: "Saint Barthélemy",
    scope: "latin-america",
    slug: "saint-barthelemy",
  },
  {
    aliases: [
      "saint helena",
      "saint helena, ascension and tristan da cunha",
      "sh",
      "shn",
      "st. helena, ascension and tristan da cunha",
    ],
    name: "Saint Helena, Ascension and Tristan da Cunha",
    scope: "africa",
    slug: "saint-helena-ascension-and-tristan-da-cunha",
  },
  {
    aliases: [
      "federation of saint christopher and nevis",
      "kn",
      "kna",
      "saint kitts and nevis",
    ],
    name: "Saint Kitts and Nevis",
    scope: "latin-america",
    slug: "saint-kitts-and-nevis",
  },
  {
    aliases: ["lc", "lca", "saint lucia"],
    name: "Saint Lucia",
    scope: "latin-america",
    slug: "saint-lucia",
  },
  {
    aliases: [
      "collectivity of saint martin",
      "collectivité de saint-martin",
      "maf",
      "mf",
      "saint martin",
      "saint martin (french part)",
    ],
    name: "Saint Martin",
    scope: "latin-america",
    slug: "saint-martin",
  },
  {
    aliases: [
      "collectivité territoriale de saint-pierre-et-miquelon",
      "pm",
      "saint pierre and miquelon",
      "spm",
    ],
    name: "Saint Pierre and Miquelon",
    scope: "north-america",
    slug: "saint-pierre-and-miquelon",
  },
  {
    aliases: ["saint vincent and the grenadines", "vc", "vct"],
    name: "Saint Vincent and the Grenadines",
    scope: "latin-america",
    slug: "saint-vincent-and-the-grenadines",
  },
  {
    aliases: [
      "independent state of samoa",
      "malo saʻoloto tutoʻatasi o sāmoa",
      "samoa",
      "ws",
      "wsm",
    ],
    name: "Samoa",
    scope: "oceania",
    slug: "samoa",
  },
  {
    aliases: [
      "most serene republic of san marino",
      "repubblica di san marino",
      "republic of san marino",
      "san marino",
      "sm",
      "smr",
    ],
    name: "San Marino",
    scope: "europe",
    slug: "san-marino",
  },
  {
    aliases: [
      "democratic republic of são tomé and príncipe",
      "república democrática de são tomé e príncipe",
      "sao tome and principe",
      "st",
      "stp",
      "são tomé and príncipe",
    ],
    name: "São Tomé and Príncipe",
    scope: "africa",
    slug: "sao-tome-and-principe",
  },
  {
    aliases: [
      "al-mamlakah al-‘arabiyyah as-su‘ūdiyyah",
      "kingdom of saudi arabia",
      "sa",
      "sau",
      "saudi",
      "saudi arabia",
    ],
    name: "Saudi Arabia",
    scope: "asia",
    slug: "saudi-arabia",
  },
  {
    aliases: [
      "republic of senegal",
      "république du sénégal",
      "sen",
      "senegal",
      "sn",
    ],
    name: "Senegal",
    scope: "africa",
    slug: "senegal",
  },
  {
    aliases: [
      "republic of serbia",
      "republika srbija",
      "rs",
      "serbia",
      "srb",
      "srbija",
      "република србија",
      "србија",
    ],
    name: "Serbia",
    scope: "europe",
    slug: "serbia",
  },
  {
    aliases: [
      "repiblik sesel",
      "republic of seychelles",
      "république des seychelles",
      "sc",
      "seychelles",
      "syc",
    ],
    name: "Seychelles",
    scope: "africa",
    slug: "seychelles",
  },
  {
    aliases: ["republic of sierra leone", "sierra leone", "sl", "sle"],
    name: "Sierra Leone",
    scope: "africa",
    slug: "sierra-leone",
  },
  {
    aliases: [
      "republic of singapore",
      "republik singapura",
      "sg",
      "sgp",
      "singapore",
      "singapura",
      "新加坡共和国",
    ],
    name: "Singapore",
    scope: "asia",
    slug: "singapore",
  },
  {
    aliases: ["sint maarten", "sint maarten (dutch part)", "sx", "sxm"],
    name: "Sint Maarten",
    scope: "latin-america",
    slug: "sint-maarten",
  },
  {
    aliases: [
      "sk",
      "slovak republic",
      "slovakia",
      "slovenská republika",
      "svk",
    ],
    name: "Slovakia",
    scope: "europe",
    slug: "slovakia",
  },
  {
    aliases: [
      "republic of slovenia",
      "republika slovenija",
      "si",
      "slovenia",
      "svn",
    ],
    name: "Slovenia",
    scope: "europe",
    slug: "slovenia",
  },
  {
    aliases: ["sb", "slb", "solomon islands"],
    name: "Solomon Islands",
    scope: "oceania",
    slug: "solomon-islands",
  },
  {
    aliases: [
      "aṣ-ṣūmāl",
      "federal republic of somalia",
      "jamhuuriyadda federaalka soomaaliya",
      "jumhūriyyat aṣ-ṣūmāl al-fiderāliyya",
      "so",
      "som",
      "somalia",
    ],
    name: "Somalia",
    scope: "africa",
    slug: "somalia",
  },
  {
    aliases: [
      "republic of south africa",
      "rsa",
      "south africa",
      "suid-afrika",
      "za",
      "zaf",
    ],
    name: "South Africa",
    scope: "africa",
    slug: "south-africa",
  },
  {
    aliases: [
      "gs",
      "sgs",
      "south georgia",
      "south georgia and the south sandwich islands",
    ],
    name: "South Georgia",
    scope: "global",
    slug: "south-georgia",
  },
  {
    aliases: [
      "kor",
      "korea, republic of",
      "kr",
      "republic of korea",
      "south korea",
      "남조선",
      "남한",
    ],
    name: "South Korea",
    scope: "asia",
    slug: "south-korea",
  },
  {
    aliases: ["republic of south sudan", "south sudan", "ss", "ssd"],
    name: "South Sudan",
    scope: "africa",
    slug: "south-sudan",
  },
  {
    aliases: ["es", "esp", "kingdom of spain", "reino de españa", "spain"],
    name: "Spain",
    scope: "europe",
    slug: "spain",
  },
  {
    aliases: [
      "democratic socialist republic of sri lanka",
      "ilaṅkai",
      "lk",
      "lka",
      "sri lanka",
    ],
    name: "Sri Lanka",
    scope: "asia",
    slug: "sri-lanka",
  },
  {
    aliases: [
      "jumhūrīyat as-sūdān",
      "republic of the sudan",
      "sd",
      "sdn",
      "sudan",
    ],
    name: "Sudan",
    scope: "africa",
    slug: "sudan",
  },
  {
    aliases: [
      "republic of suriname",
      "republiek suriname",
      "sarnam",
      "sr",
      "sranangron",
      "sur",
      "suriname",
    ],
    name: "Suriname",
    scope: "latin-america",
    slug: "suriname",
  },
  {
    aliases: [
      "sj",
      "sjm",
      "svalbard and jan mayen",
      "svalbard and jan mayen islands",
      "svalbard og jan mayen",
    ],
    name: "Svalbard and Jan Mayen",
    scope: "europe",
    slug: "svalbard-and-jan-mayen",
  },
  {
    aliases: [
      "kingdom of sweden",
      "konungariket sverige",
      "se",
      "swe",
      "sweden",
    ],
    name: "Sweden",
    scope: "europe",
    slug: "sweden",
  },
  {
    aliases: [
      "ch",
      "che",
      "schweiz",
      "suisse",
      "svizra",
      "svizzera",
      "swiss confederation",
      "switzerland",
    ],
    name: "Switzerland",
    scope: "europe",
    slug: "switzerland",
  },
  {
    aliases: [
      "al-jumhūrīyah al-ʻarabīyah as-sūrīyah",
      "sy",
      "syr",
      "syria",
      "syrian arab republic",
    ],
    name: "Syria",
    scope: "asia",
    slug: "syria",
  },
  {
    aliases: [
      "chinese taipei",
      "republic of china",
      "republic of china (taiwan)",
      "taiwan",
      "tw",
      "twn",
      "táiwān",
      "zhōnghuá mínguó",
      "中華民國",
    ],
    name: "Taiwan",
    scope: "asia",
    slug: "taiwan",
  },
  {
    aliases: [
      "republic of tajikistan",
      "tajikistan",
      "tj",
      "tjk",
      "toçikiston",
      "çumhuriyi toçikiston",
      "ҷумҳурии тоҷикистон",
    ],
    name: "Tajikistan",
    scope: "asia",
    slug: "tajikistan",
  },
  {
    aliases: [
      "jamhuri ya muungano wa tanzania",
      "tanzania",
      "tanzania, united republic of",
      "tz",
      "tza",
      "united republic of tanzania",
    ],
    name: "Tanzania",
    scope: "africa",
    slug: "tanzania",
  },
  {
    aliases: [
      "kingdom of thailand",
      "prathet",
      "ratcha anachak thai",
      "th",
      "tha",
      "thai",
      "thailand",
      "ราชอาณาจักรไทย",
    ],
    name: "Thailand",
    scope: "asia",
    slug: "thailand",
  },
  {
    aliases: [
      "democratic republic of timor-leste",
      "east timor",
      "república democrática de timor-leste",
      "repúblika demokrátika timór-leste",
      "timor",
      "timor lorosae",
      "timor-leste",
      "timór lorosa'e",
      "tl",
      "tls",
    ],
    name: "Timor-Leste",
    scope: "asia",
    slug: "timor-leste",
  },
  {
    aliases: [
      "république togolaise",
      "tg",
      "tgo",
      "togo",
      "togolese",
      "togolese republic",
    ],
    name: "Togo",
    scope: "africa",
    slug: "togo",
  },
  {
    aliases: ["tk", "tkl", "tokelau"],
    name: "Tokelau",
    scope: "oceania",
    slug: "tokelau",
  },
  {
    aliases: ["kingdom of tonga", "to", "ton", "tonga"],
    name: "Tonga",
    scope: "oceania",
    slug: "tonga",
  },
  {
    aliases: [
      "republic of trinidad and tobago",
      "trinidad and tobago",
      "tt",
      "tto",
    ],
    name: "Trinidad and Tobago",
    scope: "latin-america",
    slug: "trinidad-and-tobago",
  },
  {
    aliases: [
      "al-jumhūriyyah at-tūnisiyyah",
      "republic of tunisia",
      "tn",
      "tun",
      "tunisia",
      "tunisian republic",
    ],
    name: "Tunisia",
    scope: "africa",
    slug: "tunisia",
  },
  {
    aliases: [
      "republic of turkey",
      "republic of türkiye",
      "tr",
      "tur",
      "turkiye",
      "türkiye",
      "türkiye cumhuriyeti",
    ],
    name: "Türkiye",
    scope: "asia",
    slug: "turkiye",
  },
  {
    aliases: ["tkm", "tm", "turkmenistan"],
    name: "Turkmenistan",
    scope: "asia",
    slug: "turkmenistan",
  },
  {
    aliases: ["tc", "tca", "turks and caicos islands"],
    name: "Turks and Caicos Islands",
    scope: "latin-america",
    slug: "turks-and-caicos-islands",
  },
  {
    aliases: ["tuv", "tuvalu", "tv"],
    name: "Tuvalu",
    scope: "oceania",
    slug: "tuvalu",
  },
  {
    aliases: ["jamhuri ya uganda", "republic of uganda", "ug", "uga", "uganda"],
    name: "Uganda",
    scope: "africa",
    slug: "uganda",
  },
  {
    aliases: ["ua", "ukr", "ukraine", "ukrayina"],
    name: "Ukraine",
    scope: "europe",
    slug: "ukraine",
  },
  {
    aliases: ["ae", "are", "emirates", "uae", "united arab emirates"],
    name: "United Arab Emirates",
    scope: "asia",
    slug: "united-arab-emirates",
  },
  {
    aliases: [
      "gb",
      "gbr",
      "great britain",
      "uk",
      "united kingdom",
      "united kingdom of great britain and northern ireland",
    ],
    name: "United Kingdom",
    scope: "europe",
    slug: "united-kingdom",
  },
  {
    aliases: ["united states", "united states of america", "us", "usa"],
    name: "United States",
    scope: "north-america",
    slug: "united-states",
  },
  {
    aliases: ["um", "umi", "united states minor outlying islands"],
    name: "United States Minor Outlying Islands",
    scope: "latin-america",
    slug: "united-states-minor-outlying-islands",
  },
  {
    aliases: [
      "united states virgin islands",
      "vi",
      "vir",
      "virgin islands of the united states",
      "virgin islands, u.s.",
    ],
    name: "United States Virgin Islands",
    scope: "latin-america",
    slug: "united-states-virgin-islands",
  },
  {
    aliases: [
      "oriental republic of uruguay",
      "república oriental del uruguay",
      "uruguay",
      "ury",
      "uy",
    ],
    name: "Uruguay",
    scope: "latin-america",
    slug: "uruguay",
  },
  {
    aliases: [
      "o‘zbekiston respublikasi",
      "republic of uzbekistan",
      "uz",
      "uzb",
      "uzbekistan",
      "ўзбекистон республикаси",
    ],
    name: "Uzbekistan",
    scope: "asia",
    slug: "uzbekistan",
  },
  {
    aliases: [
      "republic of vanuatu",
      "ripablik blong vanuatu",
      "république de vanuatu",
      "vanuatu",
      "vu",
      "vut",
    ],
    name: "Vanuatu",
    scope: "oceania",
    slug: "vanuatu",
  },
  {
    aliases: [
      "holy see (vatican city state)",
      "stato della città del vaticano",
      "va",
      "vat",
      "vatican",
      "vatican city",
      "vatican city state",
    ],
    name: "Vatican City",
    scope: "europe",
    slug: "vatican-city",
  },
  {
    aliases: [
      "bolivarian republic of venezuela",
      "república bolivariana de venezuela",
      "ve",
      "ven",
      "venezuela",
      "venezuela, bolivarian republic of",
    ],
    name: "Venezuela",
    scope: "latin-america",
    slug: "venezuela",
  },
  {
    aliases: [
      "cộng hòa xã hội chủ nghĩa việt nam",
      "socialist republic of vietnam",
      "viet nam",
      "vietnam",
      "vn",
      "vnm",
    ],
    name: "Vietnam",
    scope: "asia",
    slug: "vietnam",
  },
  {
    aliases: [
      "territoire des îles wallis et futuna",
      "territory of the wallis and futuna islands",
      "wallis and futuna",
      "wf",
      "wlf",
    ],
    name: "Wallis and Futuna",
    scope: "oceania",
    slug: "wallis-and-futuna",
  },
  {
    aliases: [
      "eh",
      "esh",
      "sahrawi arab democratic republic",
      "taneẓroft tutrimt",
      "western sahara",
    ],
    name: "Western Sahara",
    scope: "africa",
    slug: "western-sahara",
  },
  {
    aliases: [
      "al-jumhūriyyah al-yamaniyyah",
      "republic of yemen",
      "ye",
      "yem",
      "yemen",
      "yemeni republic",
    ],
    name: "Yemen",
    scope: "asia",
    slug: "yemen",
  },
  {
    aliases: ["republic of zambia", "zambia", "zm", "zmb"],
    name: "Zambia",
    scope: "africa",
    slug: "zambia",
  },
  {
    aliases: ["republic of zimbabwe", "zimbabwe", "zw", "zwe"],
    name: "Zimbabwe",
    scope: "africa",
    slug: "zimbabwe",
  },
] as const;
