export const sampleUser = {
  accountType: "artist" as const,
  displayName: "Luna Eclipse",
  id: "user_demo_artist",
  username: "luna-eclipse",
};

type SampleArtistRole = "musician" | "producer";

export const sampleWorkspace = {
  id: "org_luna_collective",
  name: "Luna Collective",
  role: "owner",
  slug: "luna-collective",
  workspaceType: "artist_team" as const,
};

export const samplePlans = [
  {
    adsEnabled: true,
    audience: "artist" as const,
    canViewLiveBattles: false,
    canVoteLiveBattles: false,
    code: "artist_free",
    monthlyPrice: 0,
    name: "Artist Free",
    supportsWorkspaceSeats: false,
  },
  {
    adsEnabled: true,
    audience: "artist" as const,
    canViewLiveBattles: true,
    canVoteLiveBattles: true,
    code: "artist_lite_ads",
    monthlyPrice: 9.99,
    name: "Artist Lite",
    supportsWorkspaceSeats: false,
  },
  {
    adsEnabled: false,
    audience: "artist" as const,
    canViewLiveBattles: true,
    canVoteLiveBattles: true,
    code: "artist_team",
    monthlyPrice: 19.99,
    name: "Artist Team",
    supportsWorkspaceSeats: true,
  },
  {
    adsEnabled: true,
    audience: "fan" as const,
    canViewLiveBattles: false,
    canVoteLiveBattles: false,
    code: "fan_free",
    monthlyPrice: 0,
    name: "Fan Free",
    supportsWorkspaceSeats: false,
  },
  {
    adsEnabled: true,
    audience: "fan" as const,
    canViewLiveBattles: true,
    canVoteLiveBattles: true,
    code: "fan_lite_ads",
    monthlyPrice: 9.99,
    name: "Fan Lite",
    supportsWorkspaceSeats: false,
  },
  {
    adsEnabled: false,
    audience: "fan" as const,
    canViewLiveBattles: true,
    canVoteLiveBattles: true,
    code: "fan_family",
    monthlyPrice: 19.99,
    name: "Fan Family",
    supportsWorkspaceSeats: true,
  },
];

export const sampleArtists = [
  {
    followers: 124_000,
    genre: "R&B/Soul",
    id: "artist_luna",
    location: "Los Angeles, CA",
    name: "Luna Eclipse",
    roles: ["musician"] as SampleArtistRole[],
    username: "luna-eclipse",
    verified: true,
  },
  {
    followers: 8200,
    genre: "Electronic",
    id: "artist_neon",
    location: "Austin, TX",
    name: "Neon Pulse",
    roles: ["producer"] as SampleArtistRole[],
    username: "neon-pulse",
    verified: false,
  },
  {
    followers: 12_400,
    genre: "Electronic/Pop",
    id: "artist_alex",
    location: "Brooklyn, NY",
    name: "Alex Rivera",
    roles: ["musician", "producer"] as SampleArtistRole[],
    username: "alex-rivera",
    verified: false,
  },
];

export const sampleTracks = [
  {
    artistName: "Luna Eclipse",
    catalogItemType: "single" as const,
    duration: "3:45",
    genre: "R&B/Soul",
    id: "track_midnight_vibes",
    isForSale: true,
    plays: 12_543,
    price: 2.99,
    priceCents: 299,
    purchaseMode: "digital_download" as const,
    releaseAt: null,
    releaseStrategy: "publish_when_ready" as const,
    slug: "midnight-vibes",
    title: "Midnight Vibes",
  },
  {
    artistName: "Neon Pulse",
    catalogItemType: "beat" as const,
    duration: "4:12",
    genre: "Electronic",
    id: "track_electric_dreams",
    isForSale: true,
    plays: 8241,
    price: 2.49,
    priceCents: 7999,
    purchaseMode: "license" as const,
    releaseAt: "2026-05-10T17:00:00.000Z",
    releaseStrategy: "scheduled" as const,
    slug: "electric-dreams",
    title: "Electric Dreams",
  },
];

export const sampleCatalogItems = [
  {
    artist: {
      avatarUrl: "/diverse-user-avatars.png",
      followers: "124K",
      genre: "R&B / Soul",
      handle: "luna-eclipse",
      id: "artist_luna",
      listeners: "1.2M",
      location: "Los Angeles, CA",
      name: "Luna Eclipse",
      roles: ["musician"] as SampleArtistRole[],
      verified: true,
    },
    assets: [
      {
        duration: "3:45",
        format: "WAV",
        id: "asset_midnight_master",
        included: true,
        kind: "master" as const,
        label: "High Quality Master",
        subtitle: "24-bit WAV",
      },
      {
        duration: "3:45",
        format: "MP3",
        id: "asset_midnight_clean",
        included: true,
        kind: "clean" as const,
        label: "Radio Edit",
        subtitle: "Clean Version",
      },
      {
        id: "asset_midnight_booklet",
        included: true,
        kind: "booklet" as const,
        label: "Digital Booklet",
        subtitle: "PDF Artwork",
      },
    ],
    catalogItemType: "single" as const,
    coverArtUrl: "/summer-music-album-cover.png",
    currency: "USD",
    description:
      "A smooth R&B track perfect for late-night drives and summer evenings.",
    duration: "3:45",
    genre: "R&B / Soul",
    id: "track_midnight_vibes",
    isOwned: false,
    isPurchasable: true,
    isStreamable: true,
    licenseOptions: [],
    priceCents: 299,
    priceLabel: "$2.99",
    purchaseMode: "digital_download" as const,
    slug: "midnight-vibes",
    streamCount: "12,543",
    tags: ["R&B", "Soul"],
    title: "Midnight Vibes",
    visualContent: [
      {
        id: "visual_midnight_video",
        thumbnailUrl: "/music-battle-live-performance-video.jpg",
        title: "Official Music Video",
        type: "video" as const,
        views: "1.2M",
      },
    ],
  },
  {
    artist: {
      avatarUrl: "/diverse-user-avatars.png",
      battleRank: "#12",
      battleRecord: "18-4",
      followers: "8.2K",
      genre: "Electronic",
      handle: "neon-pulse",
      id: "artist_neon",
      listeners: "42K",
      location: "Austin, TX",
      name: "Neon Pulse",
      roles: ["producer"] as SampleArtistRole[],
      verified: false,
    },
    assets: [
      {
        duration: "4:12",
        format: "MP3",
        id: "asset_electric_tagged",
        included: true,
        kind: "tagged_mp3" as const,
        label: "Tagged Preview",
      },
      {
        duration: "4:12",
        format: "WAV",
        id: "asset_electric_wav",
        included: true,
        kind: "untagged_wav" as const,
        label: "Untagged WAV",
      },
      {
        id: "asset_electric_stems",
        included: true,
        kind: "stems" as const,
        label: "Track Stems",
        subtitle: "12 individual tracks",
      },
    ],
    bpm: 142,
    catalogItemType: "beat" as const,
    coverArtUrl: "/hip-hop-album-cover.png",
    currency: "USD",
    description: "Hard hitting trap instrumental with aggressive 808s.",
    duration: "4:12",
    genre: "Electronic",
    id: "track_electric_dreams",
    isOwned: false,
    isPurchasable: true,
    isStreamable: true,
    licenseOptions: [
      {
        currency: "USD",
        id: "license_electric_basic",
        includesStems: false,
        isExclusive: false,
        name: "Basic Lease",
        priceCents: 2999,
        priceLabel: "$29.99",
        rightsSummary: ["5,000 streams", "MP3 + WAV", "Non-exclusive"],
      },
      {
        currency: "USD",
        id: "license_electric_premium",
        includesStems: true,
        isExclusive: false,
        name: "Premium Lease",
        priceCents: 7999,
        priceLabel: "$79.99",
        rightsSummary: [
          "Unlimited streams",
          "Includes stems",
          "Commercial use",
        ],
      },
    ],
    musicalKey: "D minor",
    priceCents: 2999,
    priceLabel: "$29.99",
    purchaseMode: "license" as const,
    slug: "electric-dreams",
    streamCount: "8,241",
    tags: ["Beat", "Trap"],
    title: "Electric Dreams",
    visualContent: [],
  },
  {
    artist: {
      avatarUrl: "/diverse-user-avatars.png",
      followers: "12K",
      genre: "Electronic / Pop",
      handle: "alex-rivera",
      id: "artist_alex",
      listeners: "85K",
      location: "Brooklyn, NY",
      name: "Alex Rivera",
      roles: ["musician", "producer"] as SampleArtistRole[],
      verified: false,
    },
    assets: [
      {
        id: "asset_chronicles_album",
        included: true,
        kind: "master" as const,
        label: "Complete Album",
        subtitle: "9 tracks, FLAC",
      },
      {
        id: "asset_chronicles_artwork",
        included: true,
        kind: "artwork" as const,
        label: "Digital Artwork",
      },
    ],
    catalogItemType: "album" as const,
    coverArtUrl: "/night-music-album-cover.png",
    currency: "USD",
    description: "A neon-noir studio album exploring digital isolation.",
    genre: "Electronic / Pop",
    id: "project_midnight_chronicles",
    isOwned: true,
    isPurchasable: false,
    isStreamable: true,
    licenseOptions: [],
    priceCents: 1499,
    priceLabel: "$14.99",
    purchaseMode: "digital_download" as const,
    slug: "midnight-chronicles",
    streamCount: "8,245,100",
    tags: ["Electronic", "Pop"],
    title: "Midnight Chronicles",
    visualContent: [],
  },
];

export const sampleCart = {
  currency: "USD",
  id: null,
  itemCount: 0,
  items: [],
  subtotalCents: 0,
  totalCents: 0,
};

export const samplePurchasedCatalogItems = [
  {
    artist: "Luna Eclipse",
    artistSlug: "luna-eclipse",
    cover: "/summer-music-album-cover.png",
    downloadUrl: "/downloads/midnight-vibes.mp3",
    duration: "3:45",
    id: "track_midnight_vibes",
    priceCents: 299,
    priceLabel: "$2.99",
    productType: "track" as const,
    purchaseMode: "digital_download" as const,
    purchasedAt: "Jan 15, 2026",
    title: "Midnight Vibes",
  },
  {
    artist: "Neon Pulse",
    artistSlug: "neon-pulse",
    cover: "/hip-hop-album-cover.png",
    duration: "4:12",
    id: "track_electric_dreams",
    licenseName: "Premium Lease",
    priceCents: 7999,
    priceLabel: "$79.99",
    productType: "track" as const,
    purchaseMode: "license" as const,
    purchasedAt: "Jan 10, 2026",
    title: "Electric Dreams",
  },
];

export const sampleProjects = [
  {
    id: "project_after_dark",
    isPublic: true,
    projectType: "ep" as const,
    slug: "after-dark",
    title: "After Dark",
    trackCount: 5,
  },
];

export const sampleVideos = [
  {
    externalPlaybackUrl: null,
    id: "video_midnight_vibes_mv",
    muxPlaybackId: null,
    playbackPolicy: "public" as const,
    sourceProjectId: "project_after_dark",
    sourceProvider: "mux" as const,
    sourceTrackId: "track_midnight_vibes",
    status: "processing",
    title: "Midnight Vibes Official Video",
    verifiedOnPlatform: true,
    videoKind: "music_video" as const,
  },
];

export const samplePlaylists = [
  {
    description: "Late-night rotation",
    id: "playlist_after_hours",
    isPublic: false,
    title: "After Hours",
    trackCount: 12,
  },
];

export const sampleConversations = [
  {
    conversationType: "direct" as const,
    id: "conv_sarah",
    title: "Sarah Johnson",
    unreadCount: 2,
    updatedAt: new Date().toISOString(),
  },
];

export const sampleMessages = [
  {
    body: "Hey! I added the vocals to the track.",
    createdAt: new Date().toISOString(),
    id: "msg_1",
    senderId: "user_sarah",
    status: "read" as const,
  },
  {
    body: "Sounds great. I will review it tonight.",
    createdAt: new Date().toISOString(),
    id: "msg_2",
    senderId: sampleUser.id,
    status: "delivered" as const,
  },
];

export const sampleBattles = [
  {
    format: "best_of_5" as const,
    genre: "Hip-Hop",
    id: "battle_west_coast_showdown",
    status: "live" as const,
    title: "West Coast Showdown",
    viewerCount: 4321,
    visibility: "premium_only" as const,
  },
];

export const sampleComments = [
  {
    body: "This is amazing!",
    createdAt: new Date().toISOString(),
    id: "comment_1",
    userId: "fan_1",
    username: "nightowl",
  },
];

export const sampleLibraryOverview = {
  playlistCount: 3,
  purchaseCount: 4,
  recentPlayCount: 18,
  savedTrackCount: 22,
};

export const sampleAnalyticsOverview = {
  totalDownloads: 3421,
  totalFollowers: 1234,
  totalPlays: 12_543,
  totalRevenue: 2847.32,
};
