import {
  LEGACY_TEAM_PLAN_SEATS,
  PREMIUM_INCLUDED_SEATS,
} from "@soundkit/auth/plan-limits";

export const sampleUser = {
  accountType: "artist" as const,
  displayName: "Luna Eclipse",
  id: "user_demo_artist",
  username: "luna-eclipse",
};

type SampleArtistRole = "musician" | "producer";

export const sampleWorkspace = {
  id: "org_luna_collective",
  name: "Luna Collective",
  role: "owner",
  slug: "luna-collective",
  workspaceType: "artist_team" as const,
};

export const samplePlans = [
  {
    annualPriceCents: null,
    audience: "artist" as const,
    code: "artist_free",
    entitlements: { can_upload_music: true },
    maxSeats: 1,
    monthlyPriceCents: 0,
    name: "Artist Free",
  },
  {
    annualPriceCents: null,
    audience: "artist" as const,
    code: "soundkit_premium_artist",
    entitlements: {
      can_create_live_battles: true,
      can_host_live_streams: true,
      can_operate_paid_community: true,
      can_receive_payouts: true,
      can_sell_products: true,
      is_premium: true,
    },
    maxSeats: PREMIUM_INCLUDED_SEATS,
    monthlyPriceCents: 2299,
    name: "SoundKit Premium Artist",
  },
  {
    annualPriceCents: null,
    audience: "artist" as const,
    code: "artist_team",
    entitlements: {
      can_create_live_battles: true,
      can_operate_paid_community: true,
      can_receive_payouts: true,
      can_sell_products: true,
    },
    maxSeats: LEGACY_TEAM_PLAN_SEATS,
    monthlyPriceCents: 2499,
    name: "Artist Team",
  },
  {
    annualPriceCents: null,
    audience: "fan" as const,
    code: "fan_free",
    entitlements: { can_stream_public_content: true },
    maxSeats: 1,
    monthlyPriceCents: 0,
    name: "Fan Free",
  },
  {
    annualPriceCents: null,
    audience: "fan" as const,
    code: "soundkit_premium_fan",
    entitlements: {
      can_view_live_battles: true,
      can_vote_live_battles: true,
      can_watch_creator_streams: true,
      can_watch_vod: true,
      is_premium: true,
    },
    maxSeats: PREMIUM_INCLUDED_SEATS,
    monthlyPriceCents: 2299,
    name: "SoundKit Premium Fan",
  },
  {
    annualPriceCents: null,
    audience: "fan" as const,
    code: "fan_family",
    entitlements: {
      can_view_live_battles: true,
      can_vote_live_battles: true,
      can_watch_vod: true,
    },
    maxSeats: LEGACY_TEAM_PLAN_SEATS,
    monthlyPriceCents: 2499,
    name: "Fan Family",
  },
];

export const sampleArtists = [
  {
    followers: 124_000,
    genre: "R&B/Soul",
    id: "artist_luna",
    location: "Los Angeles, CA",
    name: "Luna Eclipse",
    roles: ["musician"] as SampleArtistRole[],
    username: "luna-eclipse",
    verified: true,
  },
  {
    followers: 8200,
    genre: "Electronic",
    id: "artist_neon",
    location: "Austin, TX",
    name: "Neon Pulse",
    roles: ["producer"] as SampleArtistRole[],
    username: "neon-pulse",
    verified: false,
  },
  {
    followers: 12_400,
    genre: "Electronic/Pop",
    id: "artist_alex",
    location: "Brooklyn, NY",
    name: "Alex Rivera",
    roles: ["musician", "producer"] as SampleArtistRole[],
    username: "alex-rivera",
    verified: false,
  },
];

export const sampleTracks = [
  {
    artistName: "Luna Eclipse",
    bpm: 96,
    catalogItemType: "single" as const,
    collaboratorCount: 0,
    coverArtUrl: "/summer-music-album-cover.png",
    duration: "3:24",
    fileAvailability: {
      adlibs: false,
      coverArt: true,
      instrumental: true,
      master: true,
      reference: false,
      session: false,
      vocals: 1,
    },
    genre: "R&B/Soul",
    id: "track_summer_nights",
    isForSale: true,
    isPublic: true,
    lyricsStatus: "missing" as const,
    musicalKey: "C Major",
    organizationId: sampleWorkspace.id,
    playbackUrl: null,
    plays: 2_400_000,
    price: 2.99,
    priceCents: 299,
    productionStatus: "complete" as const,
    purchaseMode: "digital_download" as const,
    releaseAt: null,
    releaseStrategy: "publish_when_ready" as const,
    slug: "summer-nights",
    title: "Summer Nights",
    updatedAt: "2026-04-25T12:00:00.000Z",
  },
  {
    artistName: "Luna Eclipse",
    bpm: 92,
    catalogItemType: "single" as const,
    collaboratorCount: 0,
    coverArtUrl: "/placeholder.svg",
    duration: "3:45",
    fileAvailability: {
      adlibs: false,
      coverArt: true,
      instrumental: true,
      master: true,
      reference: false,
      session: false,
      vocals: 1,
    },
    genre: "R&B/Soul",
    id: "track_midnight_vibes",
    isForSale: true,
    isPublic: true,
    lyricsStatus: "missing" as const,
    musicalKey: "Am",
    organizationId: sampleWorkspace.id,
    playbackUrl: null,
    plays: 12_543,
    price: 2.99,
    priceCents: 299,
    productionStatus: "complete" as const,
    purchaseMode: "digital_download" as const,
    releaseAt: null,
    releaseStrategy: "publish_when_ready" as const,
    slug: "midnight-vibes",
    title: "Midnight Vibes",
    updatedAt: "2026-04-24T12:00:00.000Z",
  },
  {
    artistName: "Neon Pulse",
    bpm: 128,
    catalogItemType: "beat" as const,
    collaboratorCount: 1,
    coverArtUrl: "/placeholder.svg",
    duration: "4:12",
    fileAvailability: {
      adlibs: false,
      coverArt: true,
      instrumental: true,
      master: true,
      reference: true,
      session: true,
      vocals: 0,
    },
    genre: "Electronic",
    id: "track_electric_dreams",
    isForSale: true,
    isPublic: true,
    lyricsStatus: "missing" as const,
    musicalKey: "F#m",
    organizationId: sampleWorkspace.id,
    playbackUrl: null,
    plays: 8241,
    price: 2.49,
    priceCents: 7999,
    productionStatus: "mastered" as const,
    purchaseMode: "license" as const,
    releaseAt: "2026-05-10T17:00:00.000Z",
    releaseStrategy: "scheduled" as const,
    slug: "electric-dreams",
    title: "Electric Dreams",
    updatedAt: "2026-04-24T12:00:00.000Z",
  },
];

export const sampleCatalogItems = [
  {
    artist: {
      avatarUrl: "/diverse-user-avatars.png",
      followers: "124K",
      genre: "R&B / Soul",
      handle: "luna-eclipse",
      id: "artist_luna",
      listeners: "1.2M",
      location: "Los Angeles, CA",
      name: "Luna Eclipse",
      roles: ["musician"] as SampleArtistRole[],
      verified: true,
    },
    assets: [
      {
        duration: "3:45",
        format: "WAV",
        id: "asset_midnight_master",
        included: true,
        kind: "master" as const,
        label: "High Quality Master",
        subtitle: "24-bit WAV",
      },
      {
        duration: "3:45",
        format: "MP3",
        id: "asset_midnight_clean",
        included: true,
        kind: "clean" as const,
        label: "Radio Edit",
        subtitle: "Clean Version",
      },
      {
        id: "asset_midnight_booklet",
        included: true,
        kind: "booklet" as const,
        label: "Digital Booklet",
        subtitle: "PDF Artwork",
      },
    ],
    catalogItemType: "single" as const,
    coverArtUrl: "/summer-music-album-cover.png",
    currency: "USD",
    description:
      "A smooth R&B track perfect for late-night drives and summer evenings.",
    duration: "3:45",
    genre: "R&B / Soul",
    id: "track_midnight_vibes",
    isOwned: false,
    isPurchasable: true,
    isStreamable: true,
    licenseOptions: [],
    priceCents: 299,
    priceLabel: "$2.99",
    purchaseMode: "digital_download" as const,
    slug: "midnight-vibes",
    streamCount: "12,543",
    tags: ["R&B", "Soul"],
    title: "Midnight Vibes",
    visualContent: [
      {
        id: "visual_midnight_video",
        thumbnailUrl: "/music-battle-live-performance-video.jpg",
        title: "Official Music Video",
        type: "video" as const,
        views: "1.2M",
      },
    ],
  },
  {
    artist: {
      avatarUrl: "/diverse-user-avatars.png",
      battleRank: "#12",
      battleRecord: "18-4",
      followers: "8.2K",
      genre: "Electronic",
      handle: "neon-pulse",
      id: "artist_neon",
      listeners: "42K",
      location: "Austin, TX",
      name: "Neon Pulse",
      roles: ["producer"] as SampleArtistRole[],
      verified: false,
    },
    assets: [
      {
        duration: "4:12",
        format: "MP3",
        id: "asset_electric_tagged",
        included: true,
        kind: "tagged_mp3" as const,
        label: "Tagged Preview",
      },
      {
        duration: "4:12",
        format: "WAV",
        id: "asset_electric_wav",
        included: true,
        kind: "untagged_wav" as const,
        label: "Untagged WAV",
      },
      {
        id: "asset_electric_stems",
        included: true,
        kind: "stems" as const,
        label: "Track Stems",
        subtitle: "12 individual tracks",
      },
    ],
    bpm: 142,
    catalogItemType: "beat" as const,
    coverArtUrl: "/hip-hop-album-cover.png",
    currency: "USD",
    description: "Hard hitting trap instrumental with aggressive 808s.",
    duration: "4:12",
    genre: "Electronic",
    id: "track_electric_dreams",
    isOwned: false,
    isPurchasable: true,
    isStreamable: true,
    licenseOptions: [
      {
        currency: "USD",
        id: "license_electric_basic",
        includesStems: false,
        isExclusive: false,
        name: "Basic Lease",
        priceCents: 2999,
        priceLabel: "$29.99",
        rightsSummary: ["5,000 streams", "MP3 + WAV", "Non-exclusive"],
      },
      {
        currency: "USD",
        id: "license_electric_premium",
        includesStems: true,
        isExclusive: false,
        name: "Premium Lease",
        priceCents: 7999,
        priceLabel: "$79.99",
        rightsSummary: [
          "Unlimited streams",
          "Includes stems",
          "Commercial use",
        ],
      },
    ],
    musicalKey: "D minor",
    priceCents: 2999,
    priceLabel: "$29.99",
    purchaseMode: "license" as const,
    slug: "electric-dreams",
    streamCount: "8,241",
    tags: ["Beat", "Trap"],
    title: "Electric Dreams",
    visualContent: [],
  },
  {
    artist: {
      avatarUrl: "/diverse-user-avatars.png",
      followers: "12K",
      genre: "Electronic / Pop",
      handle: "alex-rivera",
      id: "artist_alex",
      listeners: "85K",
      location: "Brooklyn, NY",
      name: "Alex Rivera",
      roles: ["musician", "producer"] as SampleArtistRole[],
      verified: false,
    },
    assets: [
      {
        id: "asset_chronicles_album",
        included: true,
        kind: "master" as const,
        label: "Complete Album",
        subtitle: "9 tracks, FLAC",
      },
      {
        id: "asset_chronicles_artwork",
        included: true,
        kind: "artwork" as const,
        label: "Digital Artwork",
      },
    ],
    catalogItemType: "album" as const,
    coverArtUrl: "/night-music-album-cover.png",
    currency: "USD",
    description: "A neon-noir studio album exploring digital isolation.",
    genre: "Electronic / Pop",
    id: "project_midnight_chronicles",
    isOwned: true,
    isPurchasable: false,
    isStreamable: true,
    licenseOptions: [],
    priceCents: 1499,
    priceLabel: "$14.99",
    purchaseMode: "digital_download" as const,
    slug: "midnight-chronicles",
    streamCount: "8,245,100",
    tags: ["Electronic", "Pop"],
    title: "Midnight Chronicles",
    visualContent: [],
  },
];

export const sampleCart = {
  currency: "USD",
  id: null,
  itemCount: 0,
  items: [],
  subtotalCents: 0,
  totalCents: 0,
};

export const samplePurchasedCatalogItems = [
  {
    artist: "Luna Eclipse",
    artistSlug: "luna-eclipse",
    cover: "/summer-music-album-cover.png",
    downloadUrl: "/downloads/midnight-vibes.mp3",
    duration: "3:45",
    id: "track_midnight_vibes",
    priceCents: 299,
    priceLabel: "$2.99",
    productType: "track" as const,
    purchaseMode: "digital_download" as const,
    purchasedAt: "Jan 15, 2026",
    title: "Midnight Vibes",
  },
  {
    artist: "Neon Pulse",
    artistSlug: "neon-pulse",
    cover: "/hip-hop-album-cover.png",
    duration: "4:12",
    id: "track_electric_dreams",
    licenseName: "Premium Lease",
    priceCents: 7999,
    priceLabel: "$79.99",
    productType: "track" as const,
    purchaseMode: "license" as const,
    purchasedAt: "Jan 10, 2026",
    title: "Electric Dreams",
  },
];

export const sampleProjects = [
  {
    collaboratorCount: 2,
    coverArtUrl: "/placeholder.svg",
    description: "A late-night EP rollout with five linked singles.",
    id: "project_after_dark",
    isPublic: true,
    progress: 65,
    projectType: "ep" as const,
    releaseDate: "2026-05-24T00:00:00.000Z",
    slug: "after-dark",
    status: "scheduled" as const,
    title: "After Dark",
    trackCount: 5,
    updatedAt: "2026-04-24T12:00:00.000Z",
  },
];

export const sampleVideos = [
  {
    creatorName: "Luna Eclipse",
    creatorUsername: "luna-eclipse",
    duration: "03:48",
    externalPlaybackUrl: null,
    id: "video_midnight_vibes_mv",
    muxPlaybackId: null,
    playbackPolicy: "public" as const,
    sourceProjectId: "project_after_dark",
    sourceProvider: "mux" as const,
    sourceTrackId: "track_midnight_vibes",
    status: "processing",
    thumbnailUrl: "/night-music-album-cover.png",
    title: "Midnight Vibes Official Video",
    verifiedOnPlatform: true,
    videoKind: "music_video" as const,
    viewCount: "284K",
  },
];

export const samplePlaylists = [
  {
    description: "Late-night rotation",
    id: "playlist_after_hours",
    isPublic: false,
    title: "After Hours",
    trackCount: 12,
  },
];

export const sampleConversations = [
  {
    conversationType: "direct" as const,
    id: "conv_sarah",
    title: "Sarah Johnson",
    unreadCount: 2,
    updatedAt: new Date().toISOString(),
  },
];

export const sampleMessages = [
  {
    body: "Hey! I added the vocals to the track.",
    createdAt: new Date().toISOString(),
    id: "msg_1",
    senderId: "user_sarah",
    status: "read" as const,
  },
  {
    body: "Sounds great. I will review it tonight.",
    createdAt: new Date().toISOString(),
    id: "msg_2",
    senderId: sampleUser.id,
    status: "delivered" as const,
  },
];

export const sampleBattles = [
  {
    featuredRank: 1,
    format: "best_of_5" as const,
    genre: "Hip-Hop",
    id: "battle_west_coast_showdown",
    isFeatured: true,
    status: "live" as const,
    title: "West Coast Showdown",
    viewerCount: 4321,
    visibility: "premium_only" as const,
  },
  {
    featuredRank: 2,
    format: "best_of_3" as const,
    genre: "Spoken Word",
    id: "battle_spoken_word_cypher",
    isFeatured: true,
    status: "live" as const,
    title: "Spoken Word Cypher",
    viewerCount: 2140,
    visibility: "public" as const,
  },
  {
    featuredRank: null,
    format: "best_of_3" as const,
    genre: "R&B/Soul",
    id: "battle_after_hours_duel",
    isFeatured: false,
    status: "scheduled" as const,
    title: "After Hours Duel",
    viewerCount: 0,
    visibility: "public" as const,
  },
  {
    featuredRank: null,
    format: "best_of_7" as const,
    genre: "Electronic",
    id: "battle_synth_city_finals",
    isFeatured: false,
    status: "completed" as const,
    title: "Synth City Finals",
    viewerCount: 18_204,
    visibility: "public" as const,
  },
];

export const sampleComments = [
  {
    body: "This is amazing!",
    createdAt: new Date().toISOString(),
    id: "comment_1",
    userId: "fan_1",
    username: "nightowl",
  },
];

export const sampleLibraryOverview = {
  playlistCount: 3,
  purchaseCount: 4,
  recentPlayCount: 18,
  savedTrackCount: 22,
  watchedCount: 7,
};

export const sampleAnalyticsOverview = {
  totalDownloads: 3421,
  totalFollowers: 1234,
  totalPlays: 12_543,
  totalRevenue: 2847.32,
};
